### ISSUE TITLE
Updating Microsoft.NET.Test.Sdk, Microsoft.TestPlatform.TestHost from 16.2.0 causes netcoreapp2.0 tests to stop working

### ISSUE THREAD

**Issue by abatishchev** [microsoft/testfx#664] opened 2019-12-01 19:39 UTC
## Description

Updating both packages from 16.2.0 to 16.3.0 causes this compiler error:

>Error	CS0234	The type or namespace name 'TestPlatform' does not exist in the namespace 'Microsoft.VisualStudio' (are you missing an assembly reference?)	Tests.Core	d:\NuGet\microsoft.net.test.sdk\16.3.0\build\netcoreapp1.0\Microsoft.NET.Test.Sdk.Program.cs

In an auto-generated file:

```c#
// <auto-generated> This file has been auto generated. </auto-generated>
using System;
[Microsoft.VisualStudio.TestPlatform.TestSDKAutoGeneratedCode]
class AutoGeneratedProgram {static void Main(string[] args){}}
```

Updating to 16.4.0 causes this exception in the Tests tab:

>[12/01/2019 11:08:54.113 AM Informational] Store opened in 0.039 sec.
[12/01/2019 11:08:57.245 AM Error] StreamJsonRpc.RemoteInvocationException: The following TestContainer was not found 'Tests.Core\bin\Debug\netcoreapp2.0\Tests.Core.dll'
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__92`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Host.TestStoreHandler.<AddSourceBasedTestsAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Extensibility.ILoggerExtensions.<CallWithCatchAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

## Steps to reproduce

1. Have unit tests project targeting netcoreapp2.0 alone
2. Install the following package

```
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.2.0" />
<PackageReference Include="Microsoft.TestPlatform.TestHost" Version="16.2.0" />
<PackageReference Include="MSTest.TestAdapter" Version="2.0.0" />
<PackageReference Include="MSTest.TestFramework" Version="2.0.0" />
```

3. Observer tests can be discovered and successfully ran using both VS and `dotnet test`.

## Expected behavior

Updating to either newer version continues to work.

## Actual behavior

Updating to either newer version doesn't work, see the error above.

## Environment

- Windows 10.0.18363 Build 18363
- Visual Studio Enterprise 16.3.10
- MSTest 2.0.0 (from NuGet.org)

**Comment by singhsarab** [comment] 2019-12-23 16:34
@abatishchev It is not very clear when the issue is reproducible as the repro steps. Is it while trying to move to 16.3.0 ?

One small correction, you don't need to have the reference to Microsoft.TestPlatform.TestHost as it is redundant.
You can simply remove that reference whole together.

**Comment by abatishchev** [comment] 2019-12-25 05:12
To both 16.3.0 and 16.4.0.

I has to install TestHost as otherwise gated build using ADO would complain that this library couldn't be found. What in general its purpose of it's optional?

**Comment by singhsarab** [comment] 2019-12-26 08:27
Microsoft.NET.Test.Sdk should bring in that dependency, you don't need to have that explicitly.

Can you share a repro, build definition or some diagnostic logs to root cause the issue.
Also, are you facing this issue with dotnet test command as well ?

**Comment by singhsarab** [comment] 2020-01-06 08:41
Gentle ping!

**Comment by abatishchev** [comment] 2020-01-06 14:13
My apologies. Let me come back from vacation on Jan 9 and reply to you with a way to reproduce the issue I've described here.

**Comment by careywalker** [comment] 2020-01-14 08:29
I am getting this same issue. I have logged an issue here as I thought that it was a Visual Studio issue. Perhaps it's a MSTest.TestAdapter issue and not a VS issue.

https://developercommunity.visualstudio.com/content/problem/883039/streamjsonrpcremoteinvocationexception-the-followi-1.html

**Comment by abatishchev** [comment] 2020-01-14 18:56
Here's a repro repo: https://github.com/jwt-dotnet/jwt/tree/temp/mstest, the branch is called `temp/mstest` where I removed xUnit and didn't add MSTest2 yet. You will be able to repro both issues from the initial posting.

**Comment by cvpoienaru** [comment] 2020-03-27 13:49
@abatishchev, unfortunately I cannot access the reproduction repo. It appears to have become unavailable in the meantime or maybe it's a private repo I don't have read permissions for. Can you please share it with me as well ?

**Comment by abatishchev** [comment] 2020-03-27 19:11
Sorry, please try now. Also ping me on Teams at _alexbat_ if needed.

**Comment by nohwnd** [comment] 2020-04-01 05:46
@pavelhorak Moving to 16.7.0 so I can release 2.1.1

**Comment by MatthewSteeples** [comment] 2020-06-04 13:54
The problem looks to be the build targets for `Microsoft.NET.Test.Sdk`

16.3 [targets](https://www.fuget.org/packages/Microsoft.NET.Test.Sdk/16.3.0) `.NETCoreApp1.0`
16.4 [targets](https://www.fuget.org/packages/Microsoft.NET.Test.Sdk/16.3.0) `.NETCoreApp2.1`

**Comment by abatishchev** [comment] 2021-01-30 23:50
Any updates on this, please?

**Comment by Haplois** [comment] 2021-07-08 01:28
The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.

**Closed by Haplois** 2021-07-08 01:28 UTC
