### ISSUE TITLE
Test Outcome is not reflected on Execute tab and test run after pipeline execution of .NET scripts

### ISSUE THREAD

**Issue by Jeyeline** [microsoft/testfx#1742] opened 2023-10-03 11:59 UTC
## Test Outcome is not reflected on the Execute tab and test run after pipeline execution of .NET scripts

Link to the defect:
[Test Outcome is not reflected on Execute tab and test run after pipeline execution of .NET scripts](https://developercommunity.visualstudio.com/t/Test-Outcome-is-not-reflected-on-Execute/10480257)

**Comment by Evangelink** [comment] 2023-10-09 07:53
Hi @Jeyeline,

I am not sure what you are expecting here. I see the related ticket is closed as not a bug with some information in which version this is fixed on AzDO.

**Comment by Jeyeline** [comment] 2023-10-09 10:02
Actually, the test outcome(pass/fail) is not update in the test plan hub after the pipeline is executed. Got to know that it is a known issue in Microsoft Visual Studio Preview version 17.2. It will be fixed in the 17.3 version which is not released now.

If there is any other alternative as workaround, it is welcome

**Comment by Evangelink** [comment] 2023-10-09 10:24
This is an issue on AzDo side so sadly we have no workaround. If you are still experiencing the issue after you upgrade, please report an issue on dev community.

**Closed by Evangelink** 2023-10-09 10:24 UTC
Labels: Needs: Attention :wave:
