### ISSUE TITLE
Test discovery failures when F# tests with spaces in names in place

### ISSUE THREAD

**Issue by mk185147** [microsoft/testfx#1395] opened 2022-11-18 14:01 UTC
It is common in F# to write test names as an English sentence. E.g., this is our test:
```FSharp
[<TestMethod>]
member this.``UnionConverter serialized and deserialized equals original``() =
    let worksOn (u:TestUnion) =
        let newU =JsonConvert.SerializeObject u |> JsonConvert.DeserializeObject<TestUnion>
        newU = u
    Check.QuickThrowOnFailure worksOn
```

When I build the test in Visual Studio then in the Visual Studio output Tests window gets this message:
```
[MSTest][Discovery][C:\Users\mk185147\Source\Repos\ncr-swt-cfr\device-automation-framework\src\Common\Communication.Domain.SocketTal.MsTest\bin\Debug\net7.0\Ncr.Devices.Automation.Common.Communication.Domain.SocketTal.MsTest.dll] MSTestAdapter failed to discover tests in class 'Ncr.Devices.Automation.Common.Communication.Domain.SocketTal.Tests.UnionConverterTests' of assembly 'C:\Users\mk185147\Source\Repos\ncr-swt-cfr\device-automation-framework\src\Common\Communication.Domain.SocketTal.MsTest\bin\Debug\net7.0\Ncr.Devices.Automation.Common.Communication.Domain.SocketTal.MsTest.dll' because Whitespace is not valid in a ManagedName (pos: 18).
```

Nevertheless, the tests with whitespaces in names are shown in Test Explorer and I am able to start them:
![image](https://user-images.githubusercontent.com/68376920/202721766-813dcb81-ba5f-46e2-b3b4-ce44aa490f1c.png)

I use today MSTest 2.2.10.

**Comment by Evangelink** [comment] 2022-11-18 15:33
Hi @mk185147! Thanks for reporting this issue. It seems to be a dupe of #941, that will be available in `3.0.0`.

**Closed by Evangelink** 2022-11-18 15:33 UTC
Labels: bug, resolution-duplicate, resolution-fixed
