### ISSUE TITLE
Timed out datarow affects subsequent datarows

### ISSUE THREAD

**Issue by dotMorten** [microsoft/testfx#728] opened 2020-08-12 05:56 UTC
## Description
When executing a test with multiple datarows, and one datarow times out, all subsequent datarows are aborted and marked failed.

## Steps to reproduce
Runt the following test:
```cs
    [TestClass]
    public class UnitTest1
    {
        [DataTestMethod]
        [DataRow(1)]
        [DataRow(2)]
        [DataRow(3)]
        [DataRow(2000)]
        [DataRow(4)]
        [DataRow(5)]
        [Timeout(500)]
        public async Task TestDataRowTimeout(int delay)
        {
            await Task.Delay(delay);
        }
    }
```

## Expected behavior

Only datarow with value `2000` times out. However row 4 and 5 are aborted with message `Test 'TestDataRowTimeout' execution has been aborted.`
The timeout doesn't apply to the combined time for all rows - that can be confirmed by setting the first few rows to be very close to 500, and added up exeeding the timeout value. If the combined time spent mattered, it would time out before making it to the slow row.

## Actual behavior
all rows after the timed out row are aborted.
![image](https://user-images.githubusercontent.com/1378165/89980031-ddb8d500-dc25-11ea-83d6-13c22ced157c.png)

## Environment
VS2019.7. .NET Core 3.1. using latest packages.

`.csproj` used:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.7.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.1.2" />
    <PackageReference Include="MSTest.TestFramework" Version="2.1.2" />
  </ItemGroup>

</Project>
```

**Comment by dotMorten** [comment] 2020-08-12 06:19
I believe the problem is that the CancellationTokenSource isn't reset after each datarow. 
When a row is timed out, this line of code is hit:
https://github.com/microsoft/testfx/blob/8fd086832b835928ab90edd36c7478323b2f4613/src/Adapter/MSTest.CoreAdapter/Execution/TestMethodInfo.cs#L792

However all subsequent datarows will be hitting this line instead, because the token is reused for all tests:
https://github.com/microsoft/testfx/blob/8fd086832b835928ab90edd36c7478323b2f4613/src/Adapter/MSTest.CoreAdapter/Execution/TestMethodInfo.cs#L787

So this basically will always return false after that point:
https://github.com/microsoft/testfx/blob/8fd086832b835928ab90edd36c7478323b2f4613/src/Adapter/MSTest.CoreAdapter/Execution/TestMethodInfo.cs#L772

**Comment by nohwnd** [comment] 2020-08-12 13:13
You are right. This is caused by sharing CancellationTokenSource across the whole test run
https://github.com/nohwnd/testfx/blob/7bc997580abbbdeb48eca0a4bd1a4dcc5e36fd94/src/Adapter/MSTest.CoreAdapter/Execution/TestMethodInfo.cs#L792

This was implemented as a reaction to not cancelling tests after timeout on dotnet core here https://github.com/microsoft/testfx/issues/608. In dotnet core there is no way to abort a thread, which is what we would need to abort a test, so instead the whole test run process is aborted as soon as a any test times out. Unfortunately this is probably the only way this can be implemented, given the limitations of the platform. 

Another way to implement this would be to abandon the thread, as we do in other places, and continue to the next test. This would allow the timeout functionality to somehow work. But would not be very transparent, because the test threads would continue running on the background, possibly locking files or other shared resources.

**Comment by dotMorten** [comment] 2020-08-12 15:00
@nohwnd I don't get this. Each datarow should be running with a new thread with a new cancellation token, so each row timeout can cancel its own thread.

I agree abandoning threads is not the way to go - that's what used to happen in [my Xamarin-port of mstest](https://github.com/dotMorten/MSTestX), and it caused a slew of problems with subsequent tests.

**Comment by nohwnd** [comment] 2021-06-23 11:12
@dotMorten 

> Each datarow should be running with a new thread with a new cancellation token, so each row timeout can cancel its own thread.

Yeah that would be great, but there is no way to abort a thread in .NET Core, and cancellation is cooperative, not preemptive. Cancellation will simply set a flag on the token. And if the task checks it, and decides that it can cancel itself the task will finish. If the task never checks, or decides not to cancel, nothing will happen, and the task will happily continue. 

So we need a more heavy handed approach. Unfortunately the next best thing is killing the whole process. 

But yeah we probably should revisit this to add better support for cancellation in async methods. We would need to propagate the token to the test method. Report if it reacted to the cancellation and either continue when cancelled, or kill the process when not aborted. And we would need to do this in a way that is backwards compatible. 

```cs
[Timeout(10000; CancelAfter = 3000)]
```

I am not sure if Tasks can pick up cancellations from context, but in any case user would have to make their code cancellable, and pass the token to methods that cancel themselves. 

But that said, this seems like a problem that is common to mstest, xunit and nunit, even though each one is handling it slightly differently. 

XUnit cancels and awaits the cancellation forever.
NUnit will complete the task which makes it report in result as completed, but the thread will still run on background, teardown will never run until it finishes. 
MSTest kills the process to avoid the problem that NUnit has. 

More in depth analysis of that is here: https://github.com/microsoft/testfx/issues/522#issuecomment-567512940

**Comment by dotMorten** [comment] 2021-06-23 16:37
I'm confused about the above response. It seems to deal with _how_ to deal with tearing down a test after a timeout, and not with the fact that each datarow is run as a new test. IMHO there should be no difference between writing 3 identical tests with 3 different parameters, vs writing one test with 3 datarows. Ie how are these really different apart from one saving me from writing a lot of repeated code ?

```cs
[Datarow(500)]
[Datarow(1000)]
[Datarow(2000)]
[Timeout(1000)]
public async Task Test(int milliseconds) => await Task.Delay(milliseconds);
```
vs.
```cs
[Timeout(1000)]
public async Task Test1() => await Task.Delay(500);
[Timeout(1000)]
public async Task Test2() => await Task.Delay(1000);
[Timeout(1000)]
public async Task Test3() => await Task.Delay(2000);
```

Currently use of datarow in tests that could potentially time out is a complete no-go, and we're forced to write all this repeated code.

**Comment by Haplois** [comment] 2021-06-23 21:03
@dotMorten, this should be fixed with out latest release. Please use `16.10.0` version of `Microsoft.NET.Test.Sdk` and the latest preview of `MSTest`; and let us know if you still have this problem.

**Comment by dotMorten** [comment] 2021-06-23 21:03
@Haplois WOOHOO! Thank you

**Closed** 2021-06-23 21:24 UTC
Labels: Triaged, enhancement

**Comment by dotMorten** [comment] 2021-06-23 21:37
@Haplois Just tried with 16.10.0 and it didn't work.
![image](https://user-images.githubusercontent.com/1378165/123171332-859b5380-d430-11eb-8bec-327cad18e20a.png)

**Comment by dotMorten** [comment] 2021-06-23 21:40
Oh nevermind. Needed to move the other dependencies to 2.2.4. In fact 16.10.0 of the SDK had no effect.

**Comment by dotMorten** [comment] 2021-06-23 23:03
Do I get this correct that you basically changed the test discoverer to return one test for each row instead of a test with multiple datarows? That would severely break all the existing test history, as these would suddenly be all new tests.

**Comment by nohwnd** [comment] 2021-06-24 10:30
@dotMorten  

> I'm confused about the above response. It seems to deal with how to deal with tearing down a test after a timeout, and not with the fact that each datarow isn't run as a new test but the outcome of the previous test can affect the outcome of the following tests. 

There are multiple things mixed together. 

1) MSTest (until the update you are testing), reported each testcase in the same test. The timeout applies to the test, that is to all testcases combined. If all testcases together take more time than the timeout, the timeout will be triggered.

2) With the update each test case is reported as a single test, and will get its own timeout.

3) BUT still, if any test times out, the timing out should trigger killing the process, which used to happen, but it seems to not happen anymore. Instead we complete a task that reports error, but the task that is running the test code still continues. It behaves the same way that NUnit is behaving. But now after the update the next test gets the chance to run, even though the timed out test is still running in the background.

```
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Threading.Tasks;

namespace TestProject12
{
    [TestClass]
    public class UnitTest1
    {
        [DataRow("tc1", 500)]
        [DataRow("tc2", 2000)]
        [DataRow("tc3", 3000)]
        [Timeout(1000)]
        [TestMethod]
        public async Task Test(string name, int milliseconds)
        {
            System.IO.File.AppendAllLines(@"C:\t\mstest.txt", new[] { $"{name} start" });
            await Task.Delay(milliseconds);
            System.IO.File.AppendAllLines(@"C:\t\mstest.txt", new[] { $"{name} end" });
        }
    }

    [TestClass]
    public class UnitTest2
    {
        [TestMethod]
        public async Task Test2()
        {
            await Task.Delay(3000);
        }
    }
}
```

```
Output: 

tc1 start
tc1 end
tc2 start
tc3 start
tc3 end
tc2 end
tc1 start
tc1 end
tc2 start
tc3 start
tc3 end
tc2 end
```


Pre update:
![image](https://user-images.githubusercontent.com/5735905/123244781-84c3f980-d4e4-11eb-939f-ebb4fd8ef3c2.png)

After update: 
![image](https://user-images.githubusercontent.com/5735905/123244931-a7561280-d4e4-11eb-907d-82eed047f182.png)
