### ISSUE TITLE
Running parallel from DeploymentItem tests from multiple test dlls in command line fails

### ISSUE THREAD

**Issue by smadala** [Microsoft/testfx#212] opened 2017-06-28 10:18 UTC
## Description
> Running test parallel in command line with multiple test dlls which has DeploymentItem tests fail to create independent Deployment environment.

## Steps to reproduce
> 
[DeplomentItemParallel.zip](https://github.com/Microsoft/testfx/files/1108294/DeplomentItemParallel.zip)

> Download above project
> Go to Unzipped directory 
> Build solution in VS
> Run below query in powershell
```
&"C:\Program Files (x86)\Microsoft Visual Studio\public2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\v
stest.console.exe" .\UnitTestProject1\bin\Debug\UnitTestProject1.dll .\UnitTestProject76\bin\Debug\UnitTestProject76.dll .\UnitTestProject10\bin\Debug\UnitTestProject10.dll .\UnitTestProject
3\bin\Debug\UnitTestProject3.dll .\UnitTestProject4\bin\Debug\UnitTestProject4.dll .\UnitTestProject5\bin\Debug\UnitTestProject5.dll .\UnitTestProject6\bin\Debug\UnitTestProject6.dll .\UnitT
estProject7\bin\Debug\UnitTestProject7.dll /parallel
```

## Expected behavior
> All tests passed with out any error and warnings.

## Actual behavior
> 
```
Microsoft (R) Test Execution Command Line Tool Version 15.0.26228.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Warning: Test Run deployment issue: Failed to copy file 'C:\Users\samadala\Downloads\UnitTestProject76\UnitTestProject76\UnitTestProject10\bin\Debug\Test.xml' to 'C:\Users\samadala\Downloads\UnitTestProject76\UnitTestProject76\TestResults\Deploy_samadala 2017-06-28 15_18_18[1]\Out\Test.xml': System.IO.IOException: The process cannot access the file 'C:\Users\samadala\Downloads\UnitTestProject76\UnitTestProject76\TestResults\Deploy_samadala 2017-06-28 15_18_18[1]\Out\Test.xml' because it is being used by another process.

Passed   TestMethod1
Passed   TestMethod1
Passed   TestMethod1
Passed   TestMethod1
Passed   TestMethod1
Passed   TestMethod1
Passed   TestMethod1
Passed   TestMethod1

Total tests: 8. Passed: 8. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 6.3952 Seconds
```

**Comment by AbhitejJohn** [comment] 2017-07-06 05:46
This happens because resources for both the assemblies, even though they are running in separate processes, get deployed to the same folder. So after completing execution for one resource, it goes ahead and deletes all its resources deployed. So if any of the resources are common(or have the same name) and tests from the other assembly are still running they fail. 
Similar to #57.

**Comment by jayaranigarg** [comment] 2017-12-27 13:55
Closing this as duplicate of #57

**Closed by jayaranigarg** 2017-12-27 13:55 UTC
Labels: bug
