### ISSUE TITLE
No cleanup with custom TestMethodAttribute?

### ISSUE THREAD

**Issue by jol64** [microsoft/testfx#721] opened 2020-06-26 16:25 UTC
## Description
There is no cleanup with custom TestMethodAttribute.

## Steps to reproduce

I am using a custom  TestMethodAttribute. Actually it is more complex than the example below, but basically it is like this:

    public class MyTestMethodAttribute : TestMethodAttribute
    {
        public override TestResult[] Execute(ITestMethod testMethod)
        {
            using (StreamWriter sw = new StreamWriter(Path.GetTempFileName()))
            {
                try
                {
                    sw.WriteLine("Hello World"); sw.Flush();
                    return base.Execute(testMethod);
                }
                catch (Exception ex)
                {
                    sw.WriteLine("Hmm?" + ex.Message); sw.Flush();
                    return new TestResult[] { new TestResult { Outcome = UnitTestOutcome.Error } };
                }
                finally
                {
                    sw.WriteLine("Good Bye"); sw.Flush();
                }
            }
        }
    }

    [TestClass]
    public class MyTests
    { 
        [MyTestMethod]
        public void Test()
        {
            Console.WriteLine("Waiting");
            Thread.Sleep(20000);
        }
    }

Now set breakpoints in catch /finally and after starting in debug mode press cancel in test explorer (within the 20s interval).

## Expected behavior
I expect that the thread running the test is aborted with a ThreadAbortedExecption that I can catch or at least clean up with finally.

The expectation may be naive though. Actually I am open to other mechanisms, but I definitely think there has to be a means to clean up. In my real scenario I am using Mutexes which are not released, and I have a dangling process that I could kill. There could be a call Abort in TestMethodAttribute, but then I´d have an easy way to share an object reference between Execute and Abort

## Actual behavior
my catch/finally code is not called at all. The file contains just "Hello World" in case of cancel.

## Environment
Visual Studio 16.6.2 on Windows 1909, vstest.console 16.6.0, mstest 16.0.29721.120

**Comment by nohwnd** [comment] 2021-06-29 14:15
Are you trying this on .NET Framework of .NET ? In .NET (.NET Core) there is not Thread.Abort, cancelling the task will just set a flag on the cancellation token and nothing is aborted. This is platform limitation, not a limitation of vstest.

**Comment by jol64** [comment] 2021-06-29 20:20
I am doing this with .NET Framework.
Do you have any suggestion on how to get this fixed? Would I have to spawn a thread that checks IsCancellationRequested and cancels my test threads somehow? Of which cancellation token?
Or what else can be done to get proper clean up?

**Comment by Evangelink** [comment] 2022-09-30 14:36
Hi @jol64,

I have tried to run your example using `MSTest v2.2.10` and `Microsoft.NET.Test.Sdk v17.3.2` and after the 20s of the `Thread.Sleep` I see that the `finally` block is correctly called. In that case, the test is marked as passed.

You are mentioning that you are expecting some timeout, so I have tweaked your example to add `[Timeout(1000)]` in addition to the `[MyTestMethod]` definition for `public void Test()`. In this case, I also correctly see the `finally` block being called after the timeout period of `1s`. In that case, the test is marked as failed because of timeout.

Maybe the issue was fixed in between the creation of the ticket and my test.

I will move forward and close this ticket. If you are still experiencing the issue, please ping us here, ideally with a new reproducer so we can investigate it.

**Closed by Evangelink** 2022-09-30 14:36 UTC
Labels: resolution-fixed, triaged
