### ISSUE TITLE
Filtering by owner attribute not supported

### ISSUE THREAD

**Issue by prawalagarwal** [Microsoft/testfx#226] opened 2017-07-18 08:57 UTC
I am trying to run some mstest v1 tests through vstest console (dev15, VS2017 latest d15rel release as on 18/07/2017). I am using test case filter to filter out the tests:

vstest.console UnitTestProject2.dll /TestCaseFilter:"Owner=abc"

This throws the error: 
Error: No tests matched the filter because it contains one or more properties that are not valid (Owner). Specify filter expression containing valid properties (TestCategory, Priority, FullyQualifiedName, Name) and try again.

Is it planned to add support for filtering via Owner attribute?

**Comment by AbhitejJohn** [comment] 2017-07-18 20:38
It would be great to have this support. [Here](https://github.com/Microsoft/testfx/blob/abd5ea3585657914490c83d5d2b4c9e732640a89/src/Adapter/MSTest.CoreAdapter/Execution/TestMethodFilter.cs#L24) is where we have a list of supported properties today. We could go and add in an owner attribute there. However I would prefer just supporting all attributes (given that this is extensible) instead of limiting the filtering logic to a finite set that would most likely be increasing.

**Comment by pvlakshm** [comment] 2017-07-20 10:34
Dupe of #201

**Closed by pvlakshm** 2017-07-20 10:34 UTC
Labels: enhancement, up-for-grabs
