### ISSUE TITLE
App.config file in unit test project causes the unit tests to not show up in text explorer

### ISSUE THREAD

**Issue by bigswede74** [Microsoft/testfx#216] opened 2017-06-30 18:46 UTC
## Description
Randomly when a App.config file is added to a unit test project, the unit tests then disappear from the test explorer.

## Steps to reproduce
> Add some nuget packages so an App.config file is created in the unit test project

## Expected behavior
> Unit test proejcts should be able to function with an App.config file

## Actual behavior
> tests disappear from test explorer

## Environment
> Visual Studio 2017 Version 15.2 (26430.14)
> Windows 10, Build version of vstest.console v15, Package version of MSTest 1.1.11
> framework .NET 4.7 and adapter MSTest.TestAdapter 1.1.11

**Comment by AbhitejJohn** [comment] 2017-07-01 08:23
@bigswede74 : This does work for us. Does the app.config have assembly redirects? Since you are on 15.2 can you set `VS_UTE_Diagnostics` system wide environment variable to `1` and help us with the logs from Output->Tests pane please? Turning this logging on should be possible through Tools->Options in 15.3. 
Also if you could share a repro, that would help greatly.

**Comment by AbhitejJohn** [comment] 2017-07-06 05:48
@bigswede74, @irguzhav : Pinging back on this.

**Comment by bigswede74** [comment] 2017-07-06 19:21
@AbhitejJohn I will try to get something back to you as soon as I can. Yes the app.config has assembly redirects from installing NuGet packages.

**Comment by AbhitejJohn** [comment] 2017-07-27 07:15
@bigswede74 : Checking back on this. Its been a while. We could alternatively close this and reopen when you have a repro/logs so we can investigate further.

**Comment by federicoce-moravia** [comment] 2017-07-27 15:24
I may have some additional information to provide, as I'm experiencing the same issue.
It seems the issue manifests when the app.config file for the test project has binding redirects for assemblies which are not referenced by the project, and don't get copied to the output directory.

NuGet added some (spurious) binding redirects for System.Runtime, System.Reflection and protobuf in my test project when I modified some unrelated packages (perhaps to consolidate?). After that, no amount of cleaning/rebuilding would allow the discovery engine to see the tests.

**Comment by AbhitejJohn** [comment] 2017-07-28 09:11
@federicoce-moravia : Thanks for those details. Can you share the redirections added as well? Is this a .Net Core test project? If yes, this sounds related to an issue in the Test SDK addressed by [this](https://github.com/Microsoft/vstest/commit/758679f5b3f55d9a8b1cc2c696a2fe48e24ef6b1) commit. Could you update Microsoft.Test.SDK to the latest pre-release and give it a shot.

**Comment by federicoce-moravia** [comment] 2017-07-28 14:10
Certainly, the binding redirects were:

```xml
<dependentAssembly>
  <assemblyIdentity name="protobuf-net" publicKeyToken="257b51d87d2e4d67" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-2.2.1.0" newVersion="2.2.1.0" />
</dependentAssembly>
<dependentAssembly>
  <assemblyIdentity name="System.Runtime.InteropServices.RuntimeInformation" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-4.0.1.0" newVersion="4.0.1.0" />
</dependentAssembly>
<dependentAssembly>
  <assemblyIdentity name="System.Runtime" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-4.1.1.0" newVersion="4.1.1.0" />
</dependentAssembly>
<dependentAssembly>
  <assemblyIdentity name="System.Reflection" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-4.1.1.0" newVersion="4.1.1.0" />
</dependentAssembly>
```

This is on a .NET Framework 4.6.2 project BTW. I believe these System.* assemblies are called façades? I apologize, I don't quite understand their purpose and the web is skimp on details. They seem to be implicit requirements for the MongoDB C# client packages. (otherwise get assembly load failure exceptions in other projects where MongoDB is actually referenced).

May

**Comment by 23min** [comment] 2017-08-08 15:53
I see the same behavior with the following app.config (redacted):

```
<?xml version="1.0" encoding="utf-8" ?>
 <configuration>
  <configSections>
  </configSections>
  <connectionStrings>
    <add name="pocDevConnectionString"
        connectionString="Data Source=HP;Initial Catalog=brakel_poc;Integrated Security=True"
        providerName="System.Data.SqlClient" />
    <add name="pocRelConnectionString"
          connectionString="Data Source=secret.cloudapp.azure.com;Initial Catalog=brakel_poc;uid=pocuser;pwd=CalculatieTool2017!"
          providerName="System.Data.SqlClient" />
  </connectionStrings>
</configuration?>
```

**Comment by AbhitejJohn** [comment] 2017-08-09 13:20
This thread totally fell off my radar. 
@23min: You are hitting https://github.com/Microsoft/testfx/issues/203. Removing the additional `?` in `<configuration?>` gets things working again.

@federicoce-moravia : Thanks for those details. Repros for me too with that config. System.Runtime 4.1.1.0 seems to be part of System.Runtime 4.3.0 nuget package and adding that to the test project drops the corresponding binary in bin\debug and things just work. For some reason whatever brought these bindingRedirects is not adding the right nuget references. 
I see another report of a similar issue [here](https://stackoverflow.com/questions/44511572/nuget-update-sets-bindingredirects-for-system-runtime-that-then-fail-at-runtime). If we have a repro, we can get help from the [CLR folks](https://github.com/dotnet/corefx/issues) to root cause this.

@bigswede74 : Are you seeing similar issues too?

**Comment by bigswede74** [comment] 2017-08-09 17:03
@AbhitejJohn Yes I have definitely seen this behavior after adding NuGet packages that add the assembly redirects. I have been just deleting the App.conifg file from the test project to fix the issue.

**Comment by bigswede74** [comment] 2017-08-11 21:58
@AbhitejJohn I am able to reproduce this issue. What do you need from me. Attached is the app.config with the assembly redirects that is causing the tests to disappear from the test explorer. When you delete the app.config from the unit test project the tests show up in the test explorer as expected.

[app.zip](https://github.com/Microsoft/testfx/files/1219188/app.zip)

**Comment by AbhitejJohn** [comment] 2017-08-12 13:42
Thanks @bigswede74, this looks similar to what @federicoce-moravia is seeing:
```
<dependentAssembly>
        <assemblyIdentity name="System.Runtime" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.1.0" newVersion="4.1.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.Extensions" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.1.0" newVersion="4.1.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Reflection" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.1.0" newVersion="4.1.1.0" />
      </dependentAssembly>
```
Do you happen to know how these entries got added to the test project?

**Comment by bigswede74** [comment] 2017-08-14 17:32
@AbhitejJohn these redirects are added when adding the below NuGet packages to the test project.

<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Castle.Core" version="4.1.1" targetFramework="net47" />
  <package id="Moq" version="4.7.99" targetFramework="net47" />
  <package id="MSTest.TestAdapter" version="1.1.11" targetFramework="net47" />
  <package id="MSTest.TestFramework" version="1.1.11" targetFramework="net47" />
  <package id="Serilog" version="2.5.0" targetFramework="net47" />
</packages>

**Comment by daniellillja** [comment] 2017-11-29 19:55
I had to have an `app.config` so I ended up removing the `MSTest.TestAdapter` and `MSTest.TestFramework` and referenced the local version of `Microsoft.VisualStudio.QualityTools.UnitTestFramework` instead.

**Comment by jayaranigarg** [comment] 2017-11-30 06:11
Apologies for late reply. 
@bigswede74 @federicoce-moravia  Are you guys still blocked on this?

**Comment by bigswede74** [comment] 2017-11-30 17:02
@jayaranigarg there has been no fix provided. The only solution I have found is to delete the app.config file.

**Comment by jayaranigarg** [comment] 2017-12-01 12:45
@bigswede74 We were caught up in a bunch of things. We are glad to know you found a workaround and are not blocked on this.

**Comment by federicoce-moravia** [comment] 2017-12-01 12:47
Somewhat the same here, we just remove the offending lines from app.config (simply entries to DLLs that are not actually referenced by these .csprojs, but forcefully added by NuGet)

**Comment by oddmanted** [comment] 2018-03-01 12:08
I am wasting a lot of time on this same issue now! Is there any solution?
Here is my App.Config file which get edited when ever I update nuget or rebuild.

### ```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <connectionStrings>
        <add name="SqlConnection" connectionString="-removed-" />
    </connectionStrings>
    <appSettings>
        <add key="AzureStorageAccountName" value="-removed-" />
        <add key="AzureStorageAccountKey" value="-removed-" />
    </appSettings>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.1.0" newVersion="4.1.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-11.0.0.0" newVersion="11.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Diagnostics.DiagnosticSource" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.2.1" newVersion="4.0.2.1" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="log4net" publicKeyToken="669e0ddf0bb1aa2a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.0.8.0" newVersion="2.0.8.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.ApplicationInsights" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.5.1.0" newVersion="2.5.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Azure.Amqp" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.2.0.0" newVersion="2.2.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Spire.Pdf" publicKeyToken="663f351905198cb3" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.2.8.2040" newVersion="4.2.8.2040" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.Serialization.Primitives" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.2.0" newVersion="4.1.2.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Threading.Tasks.Extensions" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.1.0" newVersion="4.1.1.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

**Comment by rajarajanj** [comment] 2018-03-13 09:26
@AbhitejJohn and @jayaranigarg Any resolution for this issue? Temporary workaround is fine. But, need solution for this issue.

**Comment by cltshivash** [comment] 2018-03-23 00:41
@rajarajanj This issue is related to #241. The core issue is a redirect is being added but the redirected dlls aren't present in the test output folder. Please see if the workaorund helps.

**Comment by cltshivash** [comment] 2018-05-09 06:42
@bigswede74  @rajarajanj Please check if migrating the nuget packages from package.config to package references helps.

For more details please refer to the issue on the nuget repo.
https://github.com/NuGet/Home/issues/6723

**Comment by singhsarab** [comment] 2018-05-23 11:02
Closing this issue. Please let us know if suggestion given by @cltshivash does not help.

**Closed by singhsarab** 2018-05-23 11:02 UTC
Labels: question

**Comment by ryantheleach** [comment] 2021-07-26 07:49
I got hit by this on vs 2019, when I tried to add the following to app.config:

```
  <oracle.manageddataaccess.client>
    <version number="*">
      <settings>
        <setting name="TraceLevel" value="7" />
        <setting name="TraceOption" value="1"/>
        <setting name="TraceFileLocation" value="D:\Oracle_Home\logs\"/>
      </settings>
    </version>
  </oracle.manageddataaccess.client>
  ```
  
  I'm not in a position where I'm easily able to migrate to PackageReferences instead of package.config without getting the rest of the team involved in what was supposed to be a sneaky incremental upgrade.
