### ISSUE TITLE
No/empty TRX file generated from `dotnet test`

### ISSUE THREAD

**Issue by bdukes** [microsoft/testfx#3814] opened 2024-09-11 17:47 UTC
## Describe the bug

There are no TRX result files generated when using `dotnet test`, though there are with `dotnet vstest`.

## Steps To Reproduce

1. Pull [`dotnet-test-trx` branch](https://github.com/bdukes/mstest-demo/tree/dotnet-test-trx) of [bdukes/mstest-demo](https://github.com/bdukes/mstest-demo)
2. Run `dotnet clean` to ensure a clean environment
3. Run `dotnet test --logger trx --results-directory dotnet-test-results`
4. Run `dotnet vstest **/*.Tests.dll /Logger:trx /ResultsDirectory:dotnet-vstest-results`

## Expected behavior

Both `dotnet-test-results` and `dotnet-vstest-results` folders are created with a `.trx` file with details of the test
run.

## Actual behavior

Only `dotnet-vstest-results` is created with a `.trx` file.

**Comment by Evangelink** [comment] 2024-09-12 14:46
Hi @bdukes,

`dotnet test` parameters as described here https://learn.microsoft.com/dotnet/core/tools/dotnet-test are only working for VSTest. We are working on improving the experience for the 2 platforms but while we finish this experience, you will have to refer to https://learn.microsoft.com/dotnet/core/testing/unit-testing-platform-integration-dotnet-test to pass the parameters to the new platform. 

In your case, because you are using MSTest SDK, we are overriding the behavior of `dotnet test` but only after the processing or arguments (done following VSTest pattern) and that's why nothing happens (no error about unsupported arguments nor trx/coverage...). When calling `dotnet vstest` you are short-circuiting our integration into `dotnet test` and you force reusing the VSTest handling.

Try to run `dotnet test -- --report-trx --results-directory dotnet-test-results` and you will see the `dotnet-test-results` folder created. 

Note 1: the argument for TRX is differnt in the new platform, please refer to our extensions documentation page https://learn.microsoft.com/dotnet/core/testing/unit-testing-platform-extensions.
Note 2: if you have multiple test projects, you will see one result directory per test project and not a global one. This is because, at the moment, all projects are handled separatly and the arguments passed after `--` are forwarded individually to each project. This is part of the limitations of the current hijack of `dotnet test` and something we are working on fixing. We are for now targeting the release of .NET 9 for the full support of the new platform through `dotnet test`.

I'll close the issue as `by-design` but feel free to comment or ask further guidance.

**Comment by Evangelink** [comment] 2024-09-30 15:37
Closing now as the doc update was merged.

**Closed by Evangelink** 2024-09-30 15:37 UTC
Labels: Type: Bug, Type: Docs

**Comment by czb182** [comment] 2024-11-01 16:09
I know this is closed, but I have two points.

1. I hope the final integration can also be done in LTS sdk (.net8 currently)
2. It seems odd to me that you are trying to fix integration with dotnet sdk after the fact.  Wouldn't that be the main way the testing platform is used?  This should have been seamless IMO, not work arounds and then eventually they will integrate well.

**Comment by Evangelink** [comment] 2024-11-04 08:27
> I hope the final integration can also be done in LTS sdk (.net8 currently)

The change doesn't require any update to the SDK so yes it works with any TFM.

> It seems odd to me that you are trying to fix integration with dotnet sdk after the fact. 

We are not fixing dotnet sdk. `dotnet test` command was designed specifically with VSTest in mind and not allowing any other tooling. Because VSTest has many flaws in its design, a lot of the commands are actually useless or counter intuitive/productive.
