### ISSUE TITLE
How to Hide the StackTrace of the Custom Extension Method on Assert.That From the Text Output Window?

### ISSUE THREAD

**Issue by daryllabar** [Microsoft/testfx#564] opened 2019-02-07 16:16 UTC
I've created my own extension methods on the non static `Assert` class usable via the `Assert.That` singleton in the expected manner I'm assuming is correct:
```C#
[DebuggerHidden]
public static void ExistsLineContaining(this Assert assert, string[] lines, string value, string message = null)
{
    Assert.IsTrue(lines.Count(l => l.Contains(value)) >= 1, message);
}
```
but when my test fails, the stack trace shows the ExistsLineContaining extension method as the first value in the trace:
![image](https://user-images.githubusercontent.com/9728423/52425171-6e5ea400-2ac9-11e9-9958-d828ae020df1.png)

This is really not ideal.  I can work around it slightly by putting it in a separate assembly, and turning off debug information from being generated, but this is again really not ideal, and it doesn't solve the problem of the line from showing up in the test output (but at least it's not clickable):
![image](https://user-images.githubusercontent.com/9728423/52425293-b2ea3f80-2ac9-11e9-9d96-a2f832e97601.png)
Is there any supported method to give these extension methods more of a "First Class" feel to them by preventing them from showing in the stack trace of the test output?

**Comment by karanjitsingh** [comment] 2019-02-08 05:50
@daryllabar, could you give me a sample project for me to experiment for this?

**Comment by daryllabar** [comment] 2019-02-08 15:28
Here is an example solution. 
[AssertThatStackTraceTest.zip](https://github.com/Microsoft/testfx/files/2845630/AssertThatStackTraceTest.zip)


You'll need to do a NuGet Restore to get the MSTest files, and then for some reason (if you get this error when you attempt to run the tests, Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.), you'll need to manually update the AssertThatStackTraceTest project's MSTest.TestAdapter to 1.3.2 and then back to 1.4 in order for the tests to run.

There are two tests, WithAssembly where the extension method shows up in the stack trace, and is the first line which I always tend to click on and navigate to, which isn't ideal:
![image](https://user-images.githubusercontent.com/9728423/52487556-e5f50780-2b8b-11e9-9222-8bd10b8e3354.png)

and WithNoDebuggingAssembly where the extension method still shows up, but isn't navigable when you click on it, which is better, but kind of annoying that you have to put the method in a different assembly and remove all debugging information from the assembly in order for it to work this way:
![image](https://user-images.githubusercontent.com/9728423/52487692-28b6df80-2b8c-11e9-93d5-2a2c3c878f6a.png)

**Comment by karanjitsingh** [comment] 2019-02-12 04:32
@daryllabar, extension methods are an intellitrace feature, when things compile it's still a static method that gets a call. The stack trace you're getting is the expected behavior. 

Also there's nothing MSTest can do here since it simply provides visual studio with the Exception.

**Comment by daryllabar** [comment] 2019-02-12 11:46
But how then is the Asset method hidden from the stack trace?

**Comment by karanjitsingh** [comment] 2019-02-13 07:49
@daryllabar, Good question! It seems we exclude certain types from the stack trace [here](https://github.com/Microsoft/testfx/blob/b231cade5faa80a53d367a109251b04a954e78ab/src/Adapter/MSTest.CoreAdapter/Execution/StackTraceHelper.cs#L36)

Which made me realize that we have a workaround for you, all you have to do is keep your extension method under the namespace `
Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter`

![image](https://user-images.githubusercontent.com/4632805/52695177-d1e94580-2f91-11e9-8aa6-26c8b8eca806.png)

![image](https://user-images.githubusercontent.com/4632805/52695211-e7f70600-2f91-11e9-9345-fa1e63cad945.png)

Apologies for the confusion earlier!

**Comment by acesiddhu** [comment] 2019-02-20 06:12
Closing the issue. Please make changes as @karanjitsingh suggested

**Closed by acesiddhu** 2019-02-20 06:12 UTC
