### ISSUE TITLE
Issues after upgrading from 2.2.3 to 2.2.4

### ISSUE THREAD

**Issue by jmezach** [microsoft/testfx#856] opened 2021-06-02 07:22 UTC
## Description
> **IMPORTANT**: if the defect is reproduced only in a workflow from within the Visual Studio IDE then do not report the issue here - instead, please report it using Visual Studio's "Send Feedback" option that can be accessed from the Help menu OR using this link https://developercommunity.visualstudio.com.
>
> For a defect specific to the MSTest V2 test framework, describe the issue you've observed.

After updating MSTest.TestFramework and MSTest.TestAdapter to 2.2.4 (from 2.2.3) I'm suddenly getting the following errors:

```
An exception occurred while invoking executor 'executor://mstestadapter/v2': Type 'System.Reflection.RuntimePropertyInfo' cannot be serialized. Consider marking it with the DataContractAttribute attribute, and marking all of its members you want serialized with the DataMemberAttribute attribute. Alternatively, you can ensure that the type is public and has a parameterless constructor - all public members of the type will then be serialized, and no attributes will be required.
Stack trace:
   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.ThrowInvalidDataContractException(String message, Type type)
   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.CreateDataContract(Type type)
   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.CreateDataContract(Int32 id, RuntimeTypeHandle typeHandle, Type type)
   at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.GetDataContractSkipValidation(Int32 id, RuntimeTypeHandle typeHandle, Type type)
   at System.Runtime.Serialization.DataContract.GetDataContract(RuntimeTypeHandle typeHandle, Type type, SerializationMode mode)
   at System.Runtime.Serialization.DataContractSerializer.GetDataContract(DataContract declaredTypeContract, Type declaredType, Type objectType)
   at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.InternalWriteObjectContent(XmlWriterDelegator writer, Object graph)
   at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.InternalWriteObject(XmlWriterDelegator writer, Object graph)
   at System.Runtime.Serialization.XmlObjectSerializer.InternalWriteObject(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.WriteObject(XmlDictionaryWriter writer, Object graph)
   at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.WriteObject(Stream stream, Object graph)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Helpers.DataSerializationHelper.Serialize(Object[] data)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.ObjectModel.UnitTestElement.ToTestCase()
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.UnitTestDiscoverer.SendTestCases(String source, IEnumerable`1 testElements, ITestCaseDiscoverySink discoverySink, IDiscoveryContext discoveryContext, IMessageLogger logger)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.UnitTestDiscoverer.DiscoverTestsInSource(String source, IMessageLogger logger, ITestCaseDiscoverySink discoverySink, IDiscoveryContext discoveryContext)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestExecutionManager.RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle, TestRunCancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.MSTestExecutor.RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.RunTestInternalWithExecutors(IEnumerable`1 executorUriExtensionMap, Int64 totalTests)
```

Downgrading to 2.2.3 works, although I have to perform a `dotnet clean` before doing a `dotnet test`. This also happens in CI scenario's with GitHub actions which can be seen [here](https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/runs/2725477477)

## Steps to reproduce
> What steps can reproduce the defect?
> Please share the setup, sample project, target platform (desktop, core, uap)
The only thing I changed was updating both packages from 2.2.3 to 2.2.4.

## Expected behavior
> Share the expected output
I expect my test to run as before.

## Actual behavior
> What is the behavior observed?
See the error above

## Environment
> Please share additional details about the test environment.
> Operating system, Build version of vstest.console, Package version of MSTest
> framework and adapter
Operating System: macOS 11.4, Ubuntu (latest for CI)
SDK: 5.0.300
MSTest.TestAdapter NuGet Package: 2.2.4
MSTest.TestFramework NuGet Package: 2.2.4

**Comment by xantiva** [comment] 2021-06-02 07:42
I had the same problem yesterday. It seems to be an duplicate of: https://github.com/microsoft/testfx/issues/844

**Comment by jmezach** [comment] 2021-06-02 07:48
Hmm, maybe, although that issue seems to be related to `DataTestMethod` which I'm not using in my tests at all.

**Comment by Haplois** [comment] 2021-06-02 17:27
It looks like similar, can you share a repro with us if possible? If not, we can have a quick teams call to verify to source of issue. You can reach me via [twitter dm][1].

[1]: https://twitter.com/messages/compose?recipient_id=15582470&text=issue-856

**Comment by jmezach** [comment] 2021-06-03 05:59
@haplois I'll give the pre-release mentioned in #844 a try first to see if that solves my issue.

**Comment by jmezach** [comment] 2021-06-03 06:05
@Haplois My tests run fine with `2.2.5-preview-20210531-02`, while they fail with `2.2.4` with the same error message as #844 so I think it is fair to see that this is indeed a duplicate of that issue.

**Comment by Haplois** [comment] 2021-06-03 09:10
@jmezach, thanks. Closing this a duplicate of #844.

**Closed by Haplois** 2021-06-03 09:10 UTC
