### ISSUE TITLE
Solution Explorer warnings after upgrade to 3.2.0

### ISSUE THREAD

**Issue by avivanoff** [microsoft/testfx#2173] opened 2024-01-26 06:31 UTC
After updating the unit test project to MSTest 3.2.0, the following warning shows up in the Solution Explorer:

![image](https://github.com/microsoft/testfx/assets/29612120/19ce3f78-b065-4068-ba32-52a33ec26974)

See [sample project](https://github.com/microsoft/testfx/files/14061047/UnitTestProject1.zip).

[AB#1948318](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1948318)

**Comment by avivanoff** [comment] 2024-01-26 15:17
Visual Studio 2022 17.8.5.

**Comment by Evangelink** [comment] 2024-01-26 15:32
I have asked some colleagues to test with the same VS version and your repro project and they all don't see the warning. 

Do you mind, downloading what you have attached to confirm you are seeing the warning? If you can still reproduce, could you please provide a detailed build log? Or a binlog?

**Comment by avivanoff** [comment] 2024-01-26 18:54
It only happens after you run restore from command line:

- Download an unzip the sample project.
- Open Developer Command Prompt for VS2022 and navigate to the solution folder.
- Run `msbuild /t:restore Test.sln`.
- Open solution in Visual Studio and observer the results.

**Comment by Evangelink** [comment] 2024-01-28 18:38
Thanks! I can reproduce the error but there is nothing obvious from there. The binlog doesn't contain the warning so I have the suspect that this is a VS only issue. As far as I can tell, it doesn't affect or alter running MSTest.

**Comment by avivanoff** [comment] 2024-01-29 21:36
I noticed it only happens in non-SDK-style projects.

**Comment by Evangelink** [comment] 2024-01-30 18:22
I confirm this is only non-SDK and the issue is linked to this line https://github.com/microsoft/testfx/blob/main/src/Adapter/Build/Common/MSTest.TestAdapter.targets#L34. There is an obvious bug but even when trying to fix it, I still end up with some warning that only exists in VS and doesn't show up in any binlog. I am reaching out to MSBuild team to try to get some help.

**Comment by Evangelink** [comment] 2024-01-31 16:21
There is an open PR for fixing the display and I have open an issue on MSBuild side https://github.com/dotnet/msbuild/issues/9698 as we don't seem to be responsible for the problem. At least outside of now trying to add a reference when you use the runner mode.

**Comment by Evangelink** [comment] 2024-02-05 14:08
@avivanoff As per MSBuild comment, the issue seems to be on MSBuild side and will not require changes on MSTest side so I'd like to move forward by closing this issue. I will reopen if the fix (or futher investigation) on their side requires some change on ours.

Thanks!

**Closed by Evangelink** 2024-02-05 14:08 UTC
Labels: Type: Bug, sprint, State: Blocked
