### ISSUE TITLE
If the first argument of DataRow is an array, only the first DataRow is executed

### ISSUE THREAD

**Issue by mikeKuester** [microsoft/testfx#1368] opened 2022-11-04 15:46 UTC
## Describe the bug

If the first argument in a DataRowAttribute is an array, the following DataRowAttributes are ignored / not executed.

Visual Studio 17.3.6
.NET 6 project
Microsoft.NET.Test.Sdk 17.2.0
MSTest.Test.Adapter 2.2.10
MSTest.TesFramework 2.2.10

## Steps To Reproduce

Two test methods with multiple DataRow items per test. One test with an array as first argument, one test with a simple type (non array) as first argument.

```C#
    [TestClass]
    public class DataRowAttributeTests
    {
        [TestMethod]
        [ExpectedException(typeof(ArgumentException))]
        [DataRow(1, new int[] { 1, 2, 3 }, new int[] { 1, 2 })]  // will be executed
        [DataRow(2, new int[] { 1, 2 }, new int[] { 1, 2, 3 })]  // will be executed
        public void HaveArraysSameLengthWithoutAnArrayAsFirstArgument(int ignore, int[] first, int[] second)
        {
            // this should be part of my subject under test
            if (first.Length != second.Length) throw new ArgumentException("Different length");
        }

        [TestMethod]
        [ExpectedException(typeof(ArgumentException))]
        [DataRow(new int[] { 1, 2, 3 }, new int[] { 1, 2 })]  // will be executed
        [DataRow(new int[] { 1, 2 }, new int[] { 1, 2, 3 })]  // will not be executed
        public void HaveArraysSameLength(int[] first, int[] second)
        {
            // this should be part of my subject under test
            if (first.Length != second.Length) throw new ArgumentException("Different length");            
        }
    }
```

![image](https://user-images.githubusercontent.com/93646587/200014585-1362c312-a1d7-412c-93c3-1b888e188fee.png)

Tests output
```
Building Test Projects
========== Starting test run ==========
========== Test run finished: 3 Tests (3 Passed, 0 Failed, 0 Skipped) run in 119 ms ==========
```

For the  test method **without an array** as first argument, a test for each DataRow is executed. For the one is only one test executed.

## Expected behavior

Independent of the type of the first argument, a test for each provided DataRow has to be executed.

## Actual behavior

It seems that an array as first argument causes an internal error which is not reported. Only the test for the first DataRow is executed.

## Additional context

If found this closed issue https://github.com/microsoft/testfx/issues/1180 while searching for this bug. Therefore I hope testfx is the right place for it.

UPDATE:
If I run my build and test pipeline in Azure DevOps all tests seems to be executed?!?

```YAML
pool:
  vmImage: 'windows-2022'

...

- task: VSTest@2
  displayName: 'Run tests & publish results"'
  inputs:
    testRunTitle: 'Hardware Independent'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    testAssemblyVer2: '$(testDll)'
    codeCoverageEnabled: true
    runInParallel: true
    rerunFailedTests: false
    testFiltercriteria: 'TestCategory~hardware independent'

```

```
==============================================================================
Task         : Visual Studio Test
Description  : Run unit and functional tests (Selenium, Appium, Coded UI test, etc.) using the Visual Studio Test (VsTest) runner. Test frameworks that have a Visual Studio test adapter such as MsTest, xUnit, NUnit, Chutzpah (for JavaScript tests using QUnit, Mocha and Jasmine), etc. can be run. Tests can be distributed on multiple agents using this task (version 2).
Version      : 2.210.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/vstest
==============================================================================
SystemVssConnection exists true
SystemVssConnection exists true
Running tests using vstest.console.exe runner.
======================================================
Test selector : Test assemblies
Test filter criteria : TestCategory~hardware independent
Search folder : D:\a\1\s
Action when minimum tests threshold not met : donothing
Minimum tests expected to be run: 0
VisualStudio version selected for test execution : latest
Attempting to find vstest.console from a visual studio installation with version [17.0,18.0).
Run in parallel : true
Run in isolation : false
Path to custom adapters : null
Other console options : null
Code coverage enabled : true
Diagnostics enabled : false
SystemVssConnection exists true
Run the tests locally using vstest.console.exe
========================================================
Source filter: **/bin/**/*.Tests.dll
SystemVssConnection exists true
D:\a\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.210.0\Modules\DTAExecutionHost.exe --inputFile D:\a\_temp\input_30d7ce41-5c4d-11ed-9b17-fd9af901aa24.json


  Passed Constructor_FailsWithInvalidArgument (System.Double[],System.Double[],System.Double[],System.Double[],System.Double[],System.Double[],System.Double[],System.Double[]) [< 1 ms]
  Passed Constructor_FailsWithInvalidArgument (System.Double[],System.Double[],System.Double[],System.Double[],System.Double[],System.Double[],System.Double[],System.Double[]) [< 1 ms]
  Passed Constructor_FailsWithInvalidArgument (System.Double[],System.Double[],System.Double[],System.Double[],System.Double[],System.Double[],System.Double[],System.Double[]) [< 1 ms]
  Failed Constructor_FailsWithInvalidArgument (System.Double[],System.Double[],System.Double[],System.Double[],System.Double[],System.Double[],System.Double[],System.Double[]) [< 1 ms]
  Error Message:
   Test method did not throw expected exception System.ArgumentException. 
  Failed Constructor_FailsWithInvalidArgument (System.Double[],System.Double[],System.Double[],System.Double[],System.Double[],System.Double[],System.Double[],System.Double[]) [< 1 ms]
  Error Message:
   Test method did not throw expected exception System.ArgumentException. 

```

Constructor_FailsWithInvalidArgument is my original test method with 5 DataRow items. Within Visual Studio I see only one executed test and this is valid/green.

**Comment by mikeKuester** [comment] 2022-11-04 16:30
This is really strange ...
If my first "dummy" argument is an `int` with different values, every test will be executed within VS:
![image](https://user-images.githubusercontent.com/93646587/200026558-fd9e896e-7ddd-4bf3-8ba8-5ff822fbcf58.png)

If I switch to a bool only two tests will be executed:
![image](https://user-images.githubusercontent.com/93646587/200026996-19ab4bb2-2894-451b-a247-ed8a19d4bde3.png)

😱

I think it time for weekend now!

**Comment by mikeKuester** [comment] 2022-11-04 16:32
ARGGGHHH
Adding two images in one comment doesn't work?  This should be the first image:
![image](https://user-images.githubusercontent.com/93646587/200027633-56e14049-0d1c-41d1-b151-1bdebc514f1d.png)

**Comment by Evangelink** [comment] 2022-11-04 16:45
Hey @mikeKuester! As you correctly found, there is a closed issue with the exact same problem, the fix will be shipped as part of MSTest v3.

To give you a little more context and explain you the difference between what you see in VS and in command line. Basically, VS asks MSTest to discover tests, we then return a list and VS is using each test ID as a unique identifier for run/debug. We have a bug in 2.2.3+ of MSTest where IDs are broken for parameterized tests under some circumstances. This leads to VS mixing tests and behaving like all tests have the data of the 1st test.

As for the CI, it is using a different mechanism where it's not asking for discovery then reuse information to run tests but directly runs tests hence you don't have the issue on CI.

As the issue is fixed, I will move forward by closing this issue as fixed.

Regarding ETA for MSTest v3, I sadly cannot commit better than asap. We have 3 open tickets to fix as part of this milestone.

**Closed by Evangelink** 2022-11-04 16:45 UTC
Labels: bug

**Comment by robertmclaws** [comment] 2025-02-15 05:49
This error has reared its ugly head again in 3.8. In 3.7.3 it was working fine.
