### ISSUE TITLE
Not able to get datarow attribute value in TestContext and initialization.

### ISSUE THREAD

**Issue by Baccanno** [microsoft/testfx#1355] opened 2022-10-29 17:08 UTC
This exact same issue has been raised before here and closed : https://github.com/microsoft/testfx/issues/305
There is no way to retrieve the test DataRowAttribute data in test initialization. 

People might have different reason to do so such as simply being able to create a Log file for each case.

So what is the solution or the workaround ? The only thing I can think of is cache the method arguments through an attribute inheriting from DataTestMethodAttribute and retrieve them in the init method. But it would be highly dependant on how the Execute method is operating. It would only work if tests arguments could be queued/dequeued sequentially.

We're using version 14.0.0.0 

![image](https://user-images.githubusercontent.com/3664080/198844006-8aa8d310-ad3a-4063-97b1-b8adf7630123.png)

**Comment by Evangelink** [comment] 2022-10-31 07:15
Hi @Baccanno! Thanks for the suggestion. I have looked at the linked ticket and there are multiple requests and confusion in there so I'd like to be sure of what you are trying to achieve. Do you want to be able to access to the test parameters during the test initialization (`TestInitializeAttribute`) and/or test cleanup (`TestCleanupAttribute`)? If so could you please explain your reasoning there (basically what do you want to be able to achieve doing so)?

To give some clarifications about the linked ticket:

- The `ClassInitialize` method is being run before any test of the class so it seems perfectly reasonable that you cannot access test method arguments from here. 
- The `DataRow` property of the `TestContext`, as explained in the other ticket, this is a poor naming decision that was made but this property is only populated when using the `DataSourceAttribute` and not at all when using `DataRow`, `MemberData` or `ITestDataSource`.

**Comment by Mertsch** [comment] 2022-11-24 08:05
I always have the same issue. I want `TestContext.DataRow` to be what it should be :-)
If that is not possible maybe we can get a `TestContext.TestData`?
And maybe a `TestDataAttribute` which does exactly what `DataRow` does today, but to avoid naming confusion.

Or maybe we can have the `TestData` as value in `TestContext.TestData`.
Would make life so much easier!

I am **not** in favor of `TestInitialize` with `object[]` args. I think that is a too generic approach and might cause problem with overloads in the future. And we do have `TestContext` in `TestInitialize`.

**Comment by Evangelink** [comment] 2022-11-24 14:41
It feels like something that should be generic enough to also handle `DynamicData` but also probably provide other information to user. I am not sure how far we should go (for example we could simply expose the test method object we have and that would contain the method name, signature, display name, args...).

**Comment by builder-main** [comment] 2022-11-24 16:16
> I always have the same issue. I want `TestContext.DataRow` to be what it should be :-) If that is not possible maybe we can get a `TestContext.TestData`? And maybe a `TestDataAttribute` which does exactly what `DataRow` does today, but to avoid naming confusion.
> 
> Or maybe we can have the `TestData` as value in `TestContext.TestData`. Would make life so much easier!
> 
> I am **not** in favor of `TestInitialize` with `object[]` args. I think that is a too generic approach and might cause problem with overloads in the future. And we do have `TestContext` in `TestInitialize`.

I'm not sure you're mentioning the latest because of my example, I was indeed showing what I need but don't want to do to retrieve the test parameters vs what I'd like to do that is as you perfectly said :

> I want `TestContext.DataRow` to be what it should be :-)

@Evangelink I totally agree with the `DynamicData` route as well, we have a bunch of tests using it.

**Comment by SimonCropp** [comment] 2024-09-25 05:24
@Evangelink any movement on exposing test arguments for all scenarios? i would really like to use this feature in Verify

**Comment by Evangelink** [comment] 2024-11-07 20:43
I believe and hope this is now fixed through #4015

**Closed by Evangelink** 2024-11-07 20:43 UTC
Labels: Type: Feature, State: Approved

**Comment by SimonCropp** [comment] 2024-11-07 21:51
@Evangelink thanks. whats the eta for 3.7 so i can confirm this

**Comment by Evangelink** [comment] 2024-11-08 07:47
Probably December but given we will need to focus on some other tools, I might reduce scope and try to release sooner. Also, I'll try to publish a preview version to nuget next week.

**Comment by heinrich-ulbricht** [comment] 2024-12-21 22:39
Woah this is an early Christmas gift. Searched for a possible solution TODAY, found this thread, saw it's being worked on, went to NuGet - saw it was updated YESTERDAY. And there is is, the `DataRow` value:

![Image](https://github.com/user-attachments/assets/bffff235-9f92-4112-a60c-8f52e5c69cd0)

Thank you!

**Comment by Evangelink** [comment] 2024-12-22 09:03
You are welcome! Let us know if anything is missing or not working as expected.
