### ISSUE TITLE
Inconsistent Trx result format for DataRow and DynamicData

### ISSUE THREAD

**Issue by Cjewett** [microsoft/testfx#1423] opened 2022-06-17 18:08 UTC
Recently we've noticed that newer projects will no longer display DataRow or DynamicData test results within an InnerResults of the parent. 

Example: 

```
<Results>
	<UnitTestResult executionId="ed30577d-3f3a-4c1f-98e0-587979ba6c25" testId="4176ae15-a337-4b24-8362-b99ca5a5e519" testName="DataTestMethod (2)" computerName="WCJEWETHQ01W05" duration="00:00:00.0000053" startTime="2022-06-16T23:36:47.4509772-04:00" endTime="2022-06-16T23:36:47.4519358-04:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="ed30577d-3f3a-4c1f-98e0-587979ba6c25" />
	<UnitTestResult executionId="e8b41966-1911-4af4-bf80-9c949bc66045" testId="993f3ef5-4e02-46c7-86bc-f9bfdb8104eb" testName="DyanmicDataTestMethod (1,6/16/2022 11:36:46 PM)" computerName="WCJEWETHQ01W05" duration="00:00:00.0000796" startTime="2022-06-16T23:36:47.4519358-04:00" endTime="2022-06-16T23:36:47.4569820-04:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="e8b41966-1911-4af4-bf80-9c949bc66045" />
	<UnitTestResult executionId="4d66233a-0630-4d3b-8ce7-9e2c1738fc6c" testId="fc0bd339-b2b5-406d-8fa9-6b8870bd8800" testName="TestMethod" computerName="WCJEWETHQ01W05" duration="00:00:00.0087855" startTime="2022-06-16T23:36:47.0244851-04:00" endTime="2022-06-16T23:36:47.2941538-04:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="4d66233a-0630-4d3b-8ce7-9e2c1738fc6c" />
	<UnitTestResult executionId="3c4ceefe-c00b-4d3f-afad-2bd14da1f975" testId="90feb4c9-a17d-40c2-ab8a-6138d0939ee4" testName="DyanmicDataTestMethod (2,6/16/2022 11:36:46 PM)" computerName="WCJEWETHQ01W05" duration="00:00:00.0000038" startTime="2022-06-16T23:36:47.4569820-04:00" endTime="2022-06-16T23:36:47.4569820-04:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="3c4ceefe-c00b-4d3f-afad-2bd14da1f975" />
	<UnitTestResult executionId="d2af56c7-8aab-4053-bc4a-6e572f056486" testId="bcba1b65-4beb-4cca-a806-0866c5ab6ec2" testName="DyanmicDataTestMethod (3,6/16/2022 11:36:46 PM)" computerName="WCJEWETHQ01W05" duration="00:00:00.0000031" startTime="2022-06-16T23:36:47.4569820-04:00" endTime="2022-06-16T23:36:47.4569820-04:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="d2af56c7-8aab-4053-bc4a-6e572f056486" />
	<UnitTestResult executionId="7addad8e-9053-487b-b186-fa5a00865214" testId="f183cf0e-a1ff-429b-9648-0b304caa09c3" testName="DataTestMethod (1)" computerName="WCJEWETHQ01W05" duration="00:00:00.0001490" startTime="2022-06-16T23:36:47.3031625-04:00" endTime="2022-06-16T23:36:47.4289355-04:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="7addad8e-9053-487b-b186-fa5a00865214" />
</Results>
```

Some projects that have existed within our monolithic repository will display results using the old way though.
```
<Results>
	<UnitTestResult executionId="e3d01438-9bc5-4e45-927f-745c86a5c15b" testId="13ff94ac-c450-e0a7-5955-a529040dfc97" testName="GetCapWordsTest" computerName="WCJEWETHQ01W05" duration="00:00:00.1210155" startTime="2022-06-16T21:44:38.4302866-04:00" endTime="2022-06-16T21:44:38.5512835-04:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="e3d01438-9bc5-4e45-927f-745c86a5c15b" resultType="DataDrivenTest">
		<InnerResults>
			<UnitTestResult executionId="31e50808-ce4d-4c8b-a4e9-f44913444071" parentExecutionId="e3d01438-9bc5-4e45-927f-745c86a5c15b" testId="13ff94ac-c450-e0a7-5955-a529040dfc97" testName="GetCapWordsTest (ADD)" computerName="WCJEWETHQ01W05" duration="00:00:00.0718036" startTime="2022-06-16T21:44:38.4302866-04:00" endTime="2022-06-16T21:44:38.5512835-04:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="31e50808-ce4d-4c8b-a4e9-f44913444071" dataRowInfo="1" resultType="DataDrivenDataRow" />
			<UnitTestResult executionId="d0208c87-9237-4cc7-9a55-327ac5f7fe1b" parentExecutionId="e3d01438-9bc5-4e45-927f-745c86a5c15b" testId="13ff94ac-c450-e0a7-5955-a529040dfc97" testName="GetCapWordsTest (EXCEPT)" computerName="WCJEWETHQ01W05" duration="00:00:00.0034020" startTime="2022-06-16T21:44:38.4302866-04:00" endTime="2022-06-16T21:44:38.5512835-04:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="d0208c87-9237-4cc7-9a55-327ac5f7fe1b" dataRowInfo="2" resultType="DataDrivenDataRow" />
			<UnitTestResult executionId="6ba79bc9-44f0-4574-b550-85a5fe06f2ab" parentExecutionId="e3d01438-9bc5-4e45-927f-745c86a5c15b" testId="13ff94ac-c450-e0a7-5955-a529040dfc97" testName="GetCapWordsTest (PERCENT)" computerName="WCJEWETHQ01W05" duration="00:00:00.0039467" startTime="2022-06-16T21:44:38.4302866-04:00" endTime="2022-06-16T21:44:38.5512835-04:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="6ba79bc9-44f0-4574-b550-85a5fe06f2ab" dataRowInfo="3" resultType="DataDrivenDataRow" />
			<UnitTestResult executionId="716fd344-524b-4051-87e3-9d8b49248ac9" parentExecutionId="e3d01438-9bc5-4e45-927f-745c86a5c15b" testId="13ff94ac-c450-e0a7-5955-a529040dfc97" testName="GetCapWordsTest (ALL)" computerName="WCJEWETHQ01W05" duration="00:00:00.0037892" startTime="2022-06-16T21:44:38.4302866-04:00" endTime="2022-06-16T21:44:38.5512835-04:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="716fd344-524b-4051-87e3-9d8b49248ac9" dataRowInfo="4" resultType="DataDrivenDataRow" />
			<UnitTestResult executionId="962ca7d2-c345-4afd-8ba6-5b4dcafd4475" parentExecutionId="e3d01438-9bc5-4e45-927f-745c86a5c15b" testId="13ff94ac-c450-e0a7-5955-a529040dfc97" testName="GetCapWordsTest (EXEC)" computerName="WCJEWETHQ01W05" duration="00:00:00.0043958" startTime="2022-06-16T21:44:38.4302866-04:00" endTime="2022-06-16T21:44:38.5512835-04:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="962ca7d2-c345-4afd-8ba6-5b4dcafd4475" dataRowInfo="5" resultType="DataDrivenDataRow" />
			<UnitTestResult executionId="58081981-924d-47b8-8642-68b83a01997d" parentExecutionId="e3d01438-9bc5-4e45-927f-745c86a5c15b" testId="13ff94ac-c450-e0a7-5955-a529040dfc97" testName="GetCapWordsTest (PLAN)" computerName="WCJEWETHQ01W05" duration="00:00:00.0036648" startTime="2022-06-16T21:44:38.4302866-04:00" endTime="2022-06-16T21:44:38.5512835-04:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="58081981-924d-47b8-8642-68b83a01997d" dataRowInfo="6" resultType="DataDrivenDataRow" />
			<UnitTestResult executionId="48ee6a99-e10b-4741-b940-6a664d0a7eea" parentExecutionId="e3d01438-9bc5-4e45-927f-745c86a5c15b" testId="13ff94ac-c450-e0a7-5955-a529040dfc97" testName="GetCapWordsTest (ALTER)" computerName="WCJEWETHQ01W05" duration="00:00:00.0041014" startTime="2022-06-16T21:44:38.4302866-04:00" endTime="2022-06-16T21:44:38.5512835-04:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="48ee6a99-e10b-4741-b940-6a664d0a7eea" dataRowInfo="7" resultType="DataDrivenDataRow" />
			<UnitTestResult executionId="89509246-0026-4b16-9e57-f140e3d5ef17" parentExecutionId="e3d01438-9bc5-4e45-927f-745c86a5c15b" testId="13ff94ac-c450-e0a7-5955-a529040dfc97" testName="GetCapWordsTest (EXECUTE)" computerName="WCJEWETHQ01W05" duration="00:00:00.0034415" startTime="2022-06-16T21:44:38.4302866-04:00" endTime="2022-06-16T21:44:38.5512835-04:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="89509246-0026-4b16-9e57-f140e3d5ef17" dataRowInfo="8" resultType="DataDrivenDataRow" />
			<UnitTestResult executionId="f7eb0db2-46c3-442d-a4c3-778262a21b5d" parentExecutionId="e3d01438-9bc5-4e45-927f-745c86a5c15b" testId="13ff94ac-c450-e0a7-5955-a529040dfc97" testName="GetCapWordsTest (PRECISION)" computerName="WCJEWETHQ01W05" duration="00:00:00.0038014" startTime="2022-06-16T21:44:38.4302866-04:00" endTime="2022-06-16T21:44:38.5512835-04:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="f7eb0db2-46c3-442d-a4c3-778262a21b5d" dataRowInfo="9" resultType="DataDrivenDataRow" />
			<UnitTestResult executionId="74f74595-1b2e-4dc1-8f50-efbdc6668d53" parentExecutionId="e3d01438-9bc5-4e45-927f-745c86a5c15b" testId="13ff94ac-c450-e0a7-5955-a529040dfc97" testName="GetCapWordsTest (AND)" computerName="WCJEWETHQ01W05" duration="00:00:00.0035047" startTime="2022-06-16T21:44:38.4302866-04:00" endTime="2022-06-16T21:44:38.5512835-04:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="74f74595-1b2e-4dc1-8f50-efbdc6668d53" dataRowInfo="10" resultType="DataDrivenDataRow" />
			<UnitTestResult executionId="f85eb12b-8ec6-443a-a2f7-49efeeec913c" parentExecutionId="e3d01438-9bc5-4e45-927f-745c86a5c15b" testId="13ff94ac-c450-e0a7-5955-a529040dfc97" testName="GetCapWordsTest (EXISTS)" computerName="WCJEWETHQ01W05" duration="00:00:00.0041684" startTime="2022-06-16T21:44:38.4302866-04:00" endTime="2022-06-16T21:44:38.5512835-04:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="f85eb12b-8ec6-443a-a2f7-49efeeec913c" dataRowInfo="11" resultType="DataDrivenDataRow" />
			<UnitTestResult executionId="ef6cc418-a7e9-466a-9245-1095dfb7a33e" parentExecutionId="e3d01438-9bc5-4e45-927f-745c86a5c15b" testId="13ff94ac-c450-e0a7-5955-a529040dfc97" testName="GetCapWordsTest (PRIMARY)" computerName="WCJEWETHQ01W05" duration="00:00:00.0031907" startTime="2022-06-16T21:44:38.4302866-04:00" endTime="2022-06-16T21:44:38.5512835-04:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="ef6cc418-a7e9-466a-9245-1095dfb7a33e" dataRowInfo="12" resultType="DataDrivenDataRow" />
			<UnitTestResult executionId="5340843e-50d6-4001-aca3-57eacd5b4662" parentExecutionId="e3d01438-9bc5-4e45-927f-745c86a5c15b" testId="13ff94ac-c450-e0a7-5955-a529040dfc97" testName="GetCapWordsTest (ANY)" computerName="WCJEWETHQ01W05" duration="00:00:00.0037365" startTime="2022-06-16T21:44:38.4302866-04:00" endTime="2022-06-16T21:44:38.5512835-04:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="5340843e-50d6-4001-aca3-57eacd5b4662" dataRowInfo="13" resultType="DataDrivenDataRow" />
			<UnitTestResult executionId="77ab42e3-ae57-48ae-99f7-e86ed31e11c8" parentExecutionId="e3d01438-9bc5-4e45-927f-745c86a5c15b" testId="13ff94ac-c450-e0a7-5955-a529040dfc97" testName="GetCapWordsTest (EXIT)" computerName="WCJEWETHQ01W05" duration="00:00:00.0033440" startTime="2022-06-16T21:44:38.4302866-04:00" endTime="2022-06-16T21:44:38.5512835-04:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="77ab42e3-ae57-48ae-99f7-e86ed31e11c8" dataRowInfo="14" resultType="DataDrivenDataRow" />
		</InnerResults>
	</UnitTestResult>
</Results>
```

Based on this Github issue https://github.com/microsoft/testfx/issues/1424 they sort of suggest the reason for this change is due to vstest updates, but we're using the same vstest application for all test runs. What determines the Trx format used for DataRow and DynamicData tests?

The Visual Studio version I'm using is 17.2.3.

**Comment by Evangelink** [comment] 2022-12-02 11:45
Duplicate of #1149

**Closed by Evangelink** 2022-12-02 11:45 UTC
Labels: resolution-duplicate
