### ISSUE TITLE
Request to Support Create Unit Tests for VB.NET in VS 2017

### ISSUE THREAD

**Issue by elynch100** [Microsoft/testfx#235] opened 2017-08-05 02:30 UTC
Per my issue reported in https://developercommunity.visualstudio.com/content/problem/70314/vbnet-create-unit-tests.html VS 2017 does not support Create Unit Tests. Requesting an enhancement to include functionality in later release of software.

**Comment by jayaranigarg** [comment] 2018-12-13 10:58
Closing as duplicate of https://github.com/Microsoft/testfx/issues/376

**Closed by jayaranigarg** 2018-12-13 10:58 UTC
Labels: enhancement, exp: ide
