### ISSUE TITLE
Unable to discover tests which use Windows Runtime Types

### ISSUE THREAD

**Issue by AliveDevil** [microsoft/testfx#2342] opened 2024-02-15 12:54 UTC
## Describe the bug

Using the MSTestRunner I expected that consuming WinRT Types from WinRT Components wouldn't be an issue anymore.

Test discovery output:
```
[MSTest][Discovery][MSTestComponent\TestProject1\bin\x64\Debug\net48\TestProject1.exe] Fehler beim Laden von Typen aus der Testquelle "MSTestComponent\TestProject1\bin\x64\Debug\net48\TestProject1.exe". Möglicherweise werden einige oder alle Tests in dieser Quelle nicht ermittelt.
Fehler: System.TypeLoadException: Der Windows-Runtime-Typ 'RuntimeComponent1.ITestable' wurde nicht gefunden
```
Relevant part: `TypeLoadException: Windows Runtime Type 'RuntimeComponent1.ITestable' not found`.

Running the MSTestRunner-enabled application outside of VSTest works fine.

## Steps To Reproduce

- VS2022 17.9, with workloads C++ & .NET Desktop
- Extract Repro
[MSTestComponent.zip](https://github.com/microsoft/testfx/files/14296964/MSTestComponent.zip)
- Open Solution
- Rebuild "RuntimeComponent1"
- Rebuild "TestProject1"
- Try to step into TestMethod1 through Visual Studio Test GUI

<br>

- Now add a breakpoint to TestMethod1 and Debug the MSTestRunner-part.
- Observe that the breakpoint gets hit.

## Expected behavior
Either of those:
- MSTestAdapter should use CLI-arguments through the embedded MSTestRunner to
  - Discover tests
  - Run/Debug tests
- MSTestAdapter should be able resolve Windows Runtime Types

## Actual behavior
MSTestAdapter fails to run, debug or otherwise work with types that reference Windows Runtime Types.

## Additional context
- .NET Framework 4.8 (to change away from netfx is not an option)

**Comment by Evangelink** [comment] 2024-02-15 13:19
Hi @AliveDevil,

Thank you for taking time to report this issue and to provide a reproducer!

I am able to reproduce the issue and can confirm that the issue happens only when working in compatibility mode (so going through VSTest). We are still waiting for the runner mode to be publicly enabled through VS Test Explorer.

In the meantime, I would recommend you to use the F5 / Ctrl + F5 mode of MSTest runner to run your tests. I just checked and then run without any issue.

![F5-runner](https://github.com/microsoft/testfx/assets/11340282/8cd32cfc-d38c-4647-b769-933d143c58dd)

**Comment by Evangelink** [comment] 2024-02-15 13:22
And here is what you will be seeing with VS Test Explorer when the mode will be available:

![image](https://github.com/microsoft/testfx/assets/11340282/0426556e-b859-4033-8164-3c29fcdff40b)

**Comment by AliveDevil** [comment] 2024-02-15 13:26
> We are still waiting for the runner mode to be publicly enabled through VS Test Explorer

Ah, didn't know this wan't available from the start (assumed it would be).

> meantime, I would recommend you to use the F5 / Ctrl + F5

Creating multiple debug-profiles for each test then …

> https://github.com/microsoft/testfx/issues/2342#issuecomment-1946088007

That does look good.
Can we keep this issue open until the behavior is publicly available in VSTest?

**Comment by Evangelink** [comment] 2024-02-15 17:06
Hey @drognanar, could you please post some update here when the protocol is available publicly?!

**Comment by drognanar** [comment] 2024-02-15 19:25
I'm looking into making sure the feature is enabled by default.

if you update to VS 17.10 preview 1, with the new settings experience, you should be able to open the VS's settings.json file and then add the following setting:

```json
"previewFeatures.testingToolsUnitTestingUseTestingPlatformProtocol": true
```

**Comment by Evangelink** [comment] 2024-03-17 17:28
Hi @AliveDevil,

From latest news it seems this has been postponed again and should be part of VS 17.10 preview 3 but this is sadly out of my control.

**Comment by AliveDevil** [comment] 2024-03-17 18:22
Thanks for the heads-up @Evangelink.
I can wait until the 17.10 stable release, as I don't usually install previews just for a feature I'd like to use.
In that sense rather postpone, than deliver a bad experience.

**Comment by Evangelink** [comment] 2024-03-18 10:31
Created this public ticket on VS side https://developercommunity.visualstudio.com/t/Visual-Studio-Test-Explorer-should-suppo/10618222 to make it easier to track as this is unrelated to MSTest. Please feel free to upvote the linked ticket so that it increases chances of a fix.

I'll move forward by closing this ticket because there is nothing we can do on our side, this is just waiting for a different team.

**Closed by Evangelink** 2024-03-18 10:31 UTC
Labels: Type: Bug, Area: VS, Area: VSTest, Resolution: Pending release
