### ISSUE TITLE
Data driven test are not distinguishable in Azure DevOps

### ISSUE THREAD

**Issue by RalfJ-MS** [microsoft/testfx#1759] opened 2023-10-30 14:16 UTC
## Description
We updated MSTest.Framework and MS.TestAdapter from an older version to 3.1.1. As described in similar bug reports (after updating higher than 2.2.3), we also have problems with the presentation of data driven tests in Azure DevOps.

The other bug reports are marked as done (e.g. #1026). Nevertheless, we still have the display errors. The cause of the many bug reports with version 2.2.4 was a change to the TRX file structure. 

### A simple unit test
```
[TestMethod]
[DataRow(1, 2, 3)]
[DataRow(4, 5, 6)]
[DataRow(7, 8, 9)]
public void TestDataRow_True(int a, int b, int c)
{
    Assert.IsTrue(a != b);
    Assert.IsTrue(b != c);
}
```

### TRX file with version 2.2.3
```
<UnitTestResult executionId="0528f222-df13-4370-a1c6-3618c0a8af8d" testId="4cd1cbef-5deb-4129-e598-a37923246f96" testName="TestDataRow_True" computerName="VSERVER014" duration="00:00:00.0013856" startTime="2023-10-30T11:01:06.5612557+01:00" endTime="2023-10-30T11:01:06.5631945+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="0528f222-df13-4370-a1c6-3618c0a8af8d" resultType="DataDrivenTest">
  <InnerResults>
    <UnitTestResult executionId="f4228255-a651-4320-9b06-3212c1f01626" parentExecutionId="0528f222-df13-4370-a1c6-3618c0a8af8d" testId="4cd1cbef-5deb-4129-e598-a37923246f96" testName="TestDataRow_True (1,2,3)" computerName="VSERVER014" duration="00:00:00.0001043" startTime="2023-10-30T11:01:06.5612557+01:00" endTime="2023-10-30T11:01:06.5631945+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="f4228255-a651-4320-9b06-3212c1f01626" dataRowInfo="1" resultType="DataDrivenDataRow" />
    <UnitTestResult executionId="2ae5a0d4-ce22-4a07-8eb3-c6655cb8d6f1" parentExecutionId="0528f222-df13-4370-a1c6-3618c0a8af8d" testId="4cd1cbef-5deb-4129-e598-a37923246f96" testName="TestDataRow_True (4,5,6)" computerName="VSERVER014" duration="00:00:00.0001860" startTime="2023-10-30T11:01:06.5612557+01:00" endTime="2023-10-30T11:01:06.5631945+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="2ae5a0d4-ce22-4a07-8eb3-c6655cb8d6f1" dataRowInfo="2" resultType="DataDrivenDataRow" />
    <UnitTestResult executionId="9c4f921b-f2df-439d-bce0-837d75cad21b" parentExecutionId="0528f222-df13-4370-a1c6-3618c0a8af8d" testId="4cd1cbef-5deb-4129-e598-a37923246f96" testName="TestDataRow_True (7,8,9)" computerName="VSERVER014" duration="00:00:00.0000015" startTime="2023-10-30T11:01:06.5612557+01:00" endTime="2023-10-30T11:01:06.5631945+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="9c4f921b-f2df-439d-bce0-837d75cad21b" dataRowInfo="3" resultType="DataDrivenDataRow" />
  </InnerResults>
</UnitTestResult>
```

### TRX file with version 3.1.1
```
<UnitTestResult executionId="bb80db30-7a50-47ea-b00b-cffad258385a" testId="b12faa12-ecb1-bd26-c05e-0038802ec07f" testName="TestDataRow_True (1,2,3)" computerName="VSERVER017" duration="00:00:00.0000857" startTime="2023-10-30T13:34:38.4840820+01:00" endTime="2023-10-30T13:34:38.4881797+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="bb80db30-7a50-47ea-b00b-cffad258385a" />
<UnitTestResult executionId="ce873b1a-172b-4884-945a-f9968b80f683" testId="ca2242b3-8c80-35a1-5323-2dd87c02073c" testName="TestDataRow_True (4,5,6)" computerName="VSERVER017" duration="00:00:00.0002107" startTime="2023-10-30T13:34:38.4882231+01:00" endTime="2023-10-30T13:34:38.4885271+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="ce873b1a-172b-4884-945a-f9968b80f683" />
<UnitTestResult executionId="12ebcafc-77a0-42ca-aa0a-e96d6a02a3f3" testId="3e3c4fe0-057c-e1a7-42d9-f934ddfe5cd5" testName="TestDataRow_True (7,8,9)" computerName="VSERVER017" duration="00:00:00.0000028" startTime="2023-10-30T13:34:38.4889905+01:00" endTime="2023-10-30T13:34:38.4890744+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="12ebcafc-77a0-42ca-aa0a-e96d6a02a3f3" />

<UnitTest name="TestDataRow_True (1,2,3)" storage="d:\work\2\524\s\adenetblazor.test\bin\debug\net7.0\adenetblazor.test.dll" id="b12faa12-ecb1-bd26-c05e-0038802ec07f">
  <Execution id="bb80db30-7a50-47ea-b00b-cffad258385a" />
  <TestMethod codeBase="d:\work\2\524\s\AdeNetBlazor.Test\bin\Debug\net7.0\AdeNetBlazor.Test.dll" adapterTypeName="executor://mstestadapter/v2" className="AdeNetBlazor.Test.Converter.DataRowTest" name="TestDataRow_True" />
</UnitTest>
<UnitTest name="TestDataRow_True (4,5,6)" storage="d:\work\2\524\s\adenetblazor.test\bin\debug\net7.0\adenetblazor.test.dll" id="ca2242b3-8c80-35a1-5323-2dd87c02073c">
  <Execution id="ce873b1a-172b-4884-945a-f9968b80f683" />
  <TestMethod codeBase="d:\work\2\524\s\AdeNetBlazor.Test\bin\Debug\net7.0\AdeNetBlazor.Test.dll" adapterTypeName="executor://mstestadapter/v2" className="AdeNetBlazor.Test.Converter.DataRowTest" name="TestDataRow_True" />
</UnitTest>
<UnitTest name="TestDataRow_True (7,8,9)" storage="d:\work\2\524\s\adenetblazor.test\bin\debug\net7.0\adenetblazor.test.dll" id="3e3c4fe0-057c-e1a7-42d9-f934ddfe5cd5">
  <Execution id="12ebcafc-77a0-42ca-aa0a-e96d6a02a3f3" />
  <TestMethod codeBase="d:\work\2\524\s\AdeNetBlazor.Test\bin\Debug\net7.0\AdeNetBlazor.Test.dll" adapterTypeName="executor://mstestadapter/v2" className="AdeNetBlazor.Test.Converter.DataRowTest" name="TestDataRow_True" />
</UnitTest>
```

### Display in Azure DevOps with version 2.2.3
330 tests and the first test is displayed as parent
![image](https://github.com/microsoft/testfx/assets/149389767/e69efb60-b26d-47e5-bf84-b7d3b2ec54dd)

### Display in Azure DevOps with version 3.1.1
334 tests and the first test is displayed three times
![image](https://github.com/microsoft/testfx/assets/149389767/c880a026-dc79-471f-880f-0f878ab6a6f7)

### Same behavior with defined a DisplayName
```
[TestMethod]
[DataRow(1, 2, 3, DisplayName = "First")]
[DataRow(4, 5, 6, DisplayName = "Second")]
[DataRow(7, 8, 9, DisplayName = "Third")]
public void TestDataRow_True_DisplayName(int a, int b, int c)
{
    Assert.IsTrue(a != b);
    Assert.IsTrue(b != c);
}
```
It always displays the data row test with the lowest alphabetical order three times.
![image](https://github.com/microsoft/testfx/assets/149389767/8373d761-6687-4f21-91e3-fd1c619fc3c2)

```
[TestMethod]
[DataRow(1, 2, 3, DisplayName = "Erste")]
[DataRow(4, 5, 6, DisplayName = "Zweite")]
[DataRow(7, 8, 9, DisplayName = "Dritte")]
public void TestDataRow_True_DisplayName(int a, int b, int c)
{
    Assert.IsTrue(a != b);
    Assert.IsTrue(b != c);
}
```
![image](https://github.com/microsoft/testfx/assets/149389767/801cb070-9159-4cac-b941-3ef7eff6390e)

## Expected behavior
Data driven tests can be distinguished.

## Additional context
- Agent version: 2.213.2
- Visual Studio version on build server: 17.7.34031.279

Nuget packages
```
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.7.2" />
<PackageReference Include="MSTest.TestAdapter" Version="3.1.1" />
<PackageReference Include="MSTest.TestFramework" Version="3.1.1" />
```

**Comment by engyebrahim** [comment] 2023-11-02 10:43
Hi, This is not a bug, mstest now reports data driven tests as single tests. This was done to bring parity to how xunit and nunit does it.
we have here a ticket requested Azure DevOps to update it with new mstest you can follow.
https://developercommunity.visualstudio.com/t/Incorrect-test-result-view-in-Azure-DevO/10359804?q=Incorrect+test+result+view

**Comment by RalfJ-MS** [comment] 2023-11-02 10:56
Data driven tests are displayed as a single test since version 2.2.3. This is correct. But the test should have a unique display name. Are nunit / xunit data driven tests also indistinguishable?

I enter the DisplayName "a", "b", "c" and get three tests results with the name "a". My expected behavior is not a grouping of the tests. My expected behavior is that the tests can be distinguished.

**Comment by engyebrahim** [comment] 2023-11-02 12:38
Do you have multiple target frameworks? it could be the reason you see the same test for each framework.
When you try it in local is the trx appears right for each target framework?
I tried it local and i got the right naming for tests in the trx

**Comment by RalfJ-MS** [comment] 2023-11-02 13:02
Local it works fine. It looks like this:
![image](https://github.com/microsoft/testfx/assets/149389767/b18144e8-bd59-4693-9d0f-b5562aeab7b6)

The same tests on VSTest in Azure DevOps:
![image](https://github.com/microsoft/testfx/assets/149389767/0cbf4363-a15b-4a25-85aa-e4cee1ba6b5c)

The same result within the TestPlans view in Azure DevOps:
![image](https://github.com/microsoft/testfx/assets/149389767/76d2e062-0b19-4fac-9b0b-24f8e7401777)

If I'm downloading the TRX file from the TestPlan attachment and open it with local Visual Studio "Test Results" view, the test naming is correct:
![image](https://github.com/microsoft/testfx/assets/149389767/5727778a-86a0-4279-a764-a77ac7232391)

Therefore the trx file does not contain an error.

**Comment by Evangelink** [comment] 2023-11-15 18:56
Hey @RalfJ-MS,

Issues linked to AzDO are sadly out of MSTest controls. Would you mind opening an issue on dev community? Feel free to link the issue here so you don't have to copy all the screenshots etc.

**Comment by Evangelink** [comment] 2023-12-05 12:00
I'll move forward by closing this issue as this is a bug on AzDO side.

**Closed by Evangelink** 2023-12-05 12:00 UTC
Labels: Area: AzDO, State: Blocked
