### ISSUE TITLE
MSTest V2: "No test matches the given testcase filter `TestCategory=SmokeTests" is displayed after updating to MsTest v.2.2.7

### ISSUE THREAD

**Issue by Loic12345** [microsoft/testfx#979] opened 2021-09-21 08:18 UTC
## Description
We have a test framework base on .NET Framework 4.8 for Windows tests and use Jenkins in our CI. My team updated MsTest to the latest version (it's v.2.2.7 for now) by deleting the references for the 'old' version and installing the packages below via Nuget in all .csproj files.

PM> Install-Package MSTest.TestAdapter -Version 2.2.7
PM> Install-Package MSTest.TestFramework -Version 2.2.7

All tests successfully run locally but no via Jenkins. 

## Expected behavior
In Jenkins we use a script that filters the tests via TestCategory=SmokeTests in .dlls. And it works great before upgrading to v.2.2.7 and we get the results.

## Actual behavior
After the upgrading to the latest version we see the following error in the Jenkins .log file:
![image](https://user-images.githubusercontent.com/85739971/134136370-30656ba0-5ff8-496c-be62-e349f10daa88.png)

And we don't get the test results. Is there any changes related to the TestCategory filtering in MsTest v.2?

**Comment by Evangelink** [comment] 2022-10-31 17:08
Hi @Loic12345. I will move forward by closing this issue as we cannot reproduce and you didn't provide any repro case. Please feel free to comment and provide some repro and I will reopen the issue.

**Closed by Evangelink** 2022-10-31 17:08 UTC
Labels: resolution-cannot-reproduce
