### ISSUE TITLE
Passing emoji string in [DataRow] causes error in UTF8 encoding/decoding

### ISSUE THREAD

**Issue by dhhoang** [Microsoft/testfx#463] opened 2018-07-20 19:08 UTC
## Description
I don't know whether this issue should be in CoreCLR/Corefx, but I am unable to reproduce it outside MSTest environment.
I'm trying to pass an emoji string as parameter to `[DataRow]` but ran into the issues where UTF8 encoding back and forth produces unequal strings.

## Steps to reproduce
The following test should pass, but it fails
```csharp
[DataRow("😀 😁 😂 🤣 😃 😄 😅 😆 😉")]
[TestMethod]
public void DecodeString(string str)
{
    var bytes = Encoding.UTF8.GetBytes(str);
    var decoded = Encoding.UTF8.GetString(bytes);
    Assert.AreEqual(str, decoded);
}
```

## Expected behavior
> Parameter `str` and variable `decoded` should be equal.

## Actual behavior
```
Failed   DecodeString (😀 =� =� >� =� =� =� 😆 😉)
Error Message:
 Assert.AreEqual failed. Expected:<😀 =� =� >� =� =� =� 😆 😉>. Actual:<😀 =� =� >� =� =� =� 😆 😉>. 

```

## Environment
OS=macOS Sierra 10.12.6 (16G1510) [Darwin 16.7.0]  
Intel Core i5-7360U CPU 2.30GHz (Kaby Lake), 1 CPU, 4 logical and 2 physical cores
.NET Core SDK=2.1.301  
  [Host]     : .NET Core 2.1.1 (CoreCLR 4.6.26606.02, CoreFX 4.6.26606.05), 64bit RyuJIT

**Comment by mayankbansal018** [comment] 2018-08-07 08:15
@dhhoang , I tried this on windows machines for both dotnet core, & full clr, & could not reproduce this?
Can you try it out once on a windows machine, & see if it works for you as well?

@pvlakshm did you try it on a mac machine, or Windows?

**Comment by pvlakshm** [comment] 2018-08-07 11:34
I tried it on a Windows machine.

**Comment by dhhoang** [comment] 2018-08-07 17:01
@mayankbansal018 This issue doesn't happen on my Windows either.  
On my Mac I upgraded .Net SDK to 2.1.302 and the problem still persists.

**Comment by mayankbansal018** [comment] 2018-08-08 11:25
@dhhoang , I tried it on Linux

dotnet --info
.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.4/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

& could not reproduce the issue, will try it on a macOS next

**Comment by nigurr** [comment] 2018-08-09 10:04
```
     [TestMethod]
        [DataRow("😀 😁 😂 🤣 😃 😄 😅 😆 😉")]
        public void TestMethod2(string str)
        {
            var smi = "😀 😁 😂 🤣 😃 😄 😅 😆 😉";

            var smiBytes = Encoding.UTF8.GetBytes(smi);
            var defBytes = Encoding.UTF8.GetBytes(str);

            System.Console.WriteLine(ByteArrayCompare(smiBytes, defBytes));

            System.Console.WriteLine(string.Equals(Encoding.UTF8.GetString(smiBytes), Encoding.UTF8.GetString(defBytes)));

            System.Console.WriteLine(string.Equals(Encoding.UTF8.GetString(smiBytes), smi));
            System.Console.WriteLine(string.Equals(Encoding.UTF8.GetString(defBytes), smi));


            Assert.IsFalse(true);
        }
```

**Comment by mayankbansal018** [comment] 2018-08-09 11:53
@dhhoang , I tried this with xUnit adapter, & the test fail over there as well. This issue seems to belong to dotnet core, can you please open a bug on [corefx](https://github.com/dotnet/corefx)?

```
public class UnitTest1
    {
        [Theory]
        [InlineData("😀 😁 😂 🤣 😃 😄 😅 😆 😉")]
        public void Test1(string str)
        {
            var smi = "😀 😁 😂 🤣 😃 😄 😅 😆 😉";

            var smiBytes = Encoding.UTF8.GetBytes(smi);
            var defBytes = Encoding.UTF8.GetBytes(str);

            Console.OutputEncoding = Encoding.UTF8;
            Console.WriteLine(string.Equals(str, smi));
            Console.WriteLine(ByteArrayCompare(smiBytes, defBytes));
            Console.WriteLine(str);
            Console.WriteLine(smi);

            var bytes = Encoding.UTF8.GetBytes(str);
            var decoded = Encoding.UTF8.GetString(bytes);
            Assert.Equal(str, decoded);
        }

        private static bool ByteArrayCompare(byte[] a1, byte[] a2)
        {
            if (a1.Length != a2.Length)
                return false;

            for (int i = 0; i < a1.Length; i++)
                if (a1[i] != a2[i])
                    return false;

            return true;
        }
    }
```

**Comment by acesiddhu** [comment] 2018-08-17 09:32
@dhhoang I am closing the issue. can you follow up with corefx as Mayank suggested. Let me know if you have any further queries

**Closed by acesiddhu** 2018-08-17 09:32 UTC
Labels: bug, need-additional-info
