### ISSUE TITLE
Strong-named .NET Core 3.0 Assemblies causes Test Initialize/Cleanup to fail

### ISSUE THREAD

**Issue by dotMorten** [Microsoft/testfx#539] opened 2018-12-12 21:47 UTC
## Description
After strong-naming my assembly and unit tests, all tests that have a TestCleanup or TestInitialize fail with the following error:

```
Test Name:	Constructor_DefaultConstructor_SetsEventNameToLoaded
Test FullName:   Microsoft.Xaml.Interactions.UnitTests.EventTriggerTest.Constructor_DefaultConstructor_SetsEventNameToLoaded
Test Source:	E:\GitHub\dotMorten\XamlBehaviorsWpf\Test\UnitTests\EventTriggerTests.cs : line 120
Test Outcome:	Failed
Test Duration:	0:00:00.0012054

Result StackTrace:	
at Microsoft.Xaml.Interactions.UnitTests.EventTriggerTest.Setup()

TestCleanup Stack Trace
   at Microsoft.Xaml.Interactions.UnitTests.EventTriggerTest.Teardown()
Result Message:	
Initialization method Microsoft.Xaml.Interactions.UnitTests.EventTriggerTest.Setup threw exception. System.IO.FileLoadException: The given assembly name or codebase, 'E:\GitHub\dotMorten\XamlBehaviorsWpf\Test\UnitTests.NetCore\bin\Debug\netcoreapp3.0\Microsoft.Xaml.Behaviors.dll', was invalid..
TestCleanup method Microsoft.Xaml.Interactions.UnitTests.EventTriggerTest.Teardown threw exception. System.IO.FileLoadException: System.IO.FileLoadException: The given assembly name or codebase, 'E:\GitHub\dotMorten\XamlBehaviorsWpf\Test\UnitTests.NetCore\bin\Debug\netcoreapp3.0\Microsoft.Xaml.Behaviors.dll', was invalid..
```

## Steps to reproduce
To reproduce grab this commit which added the strong-name, and run the .NET Core unit tests:
https://github.com/dotMorten/XamlBehaviorsWpf/commit/d8c0fe4d8352d28c7edbded0849acdf4db207519
Note that all test classes that have initialize/cleanup members fail. Also note that all the NetFX tests pass (those are strongnamed too).

## Expected behavior
Compare to the commit before strong-naming was added and notice the tests are now passing:
https://github.com/dotMorten/XamlBehaviorsWpf/commit/3cb84d2e790937112988871ffefb5243276b3e9d

**Comment by abhishkk** [comment] 2018-12-20 11:09
@dotMorten 
We checked that your changes are in https://github.com/Microsoft/XamlBehaviorsWpf
So i took a clone of the repo and tried to build and run the tests from VS.
190 tests were discovered and all ran successfully. 

If you still facing the issue, can you please share the exact repro steps with us?

**Comment by abhishkk** [comment] 2018-12-26 11:34
@dotMorten Any updates here?

**Comment by abhishkk** [comment] 2019-01-03 10:33
@dotMorten 
I tried the scenario and was able to reproduce the issue. I came up with following conclusions after trying various scenarios:
1. Problem is not with TestInitialize/TestCleanup but with the content of it which is `Interaction.ShouldRunInDesignMode = true;` 
2. The issue is not with the mstest adapter but with the strong named .NET core `Microsoft.Xaml.Behaviors.dll `itself. Issue can be reproduced with any adapter (NUnit or XUnit)

Exaplanation:
`Microsoft.Xaml.Behaviors.dll` is referenced first time from `TestInitialize` and thus process attempts to load it. This assembly has some issues (may be because of way it is signed) and thus assembly load fails causing the test to fail.

Scenarios tried: 
1. To prove the same, I created a new unit test project and added test method with below content:
```
        [TestMethod]
        public void TestMethod1()
        {
            Interaction.ShouldRunInDesignMode = true;
        }
```

This test method doesn't have any TestInitialize/TestCleanup. Still the test fails with same exception. Thus proving the TestInitialize/TestCleanup is not the culprit.
2. I further tested the scenario by creating new NUnit test project and XUnit test project with test method containing same line `Interaction.ShouldRunInDesignMode = true;` and tests fail in those adapters as well. Thus proving problem is not with mstest adapter or any adapter.

Can you have a look if something is being missed while strong naming the assembly?

**Comment by dotMorten** [comment] 2019-01-03 22:16
I'll take a look, but the only difference made was the strong naming, which caused it to break. See commit comparisons here:
https://github.com/Microsoft/XamlBehaviorsWpf/compare/3cb84d2...d8c0fe4
Signing with the key is pretty straightforward

**Comment by abhishkk** [comment] 2019-01-08 09:33
@dotMorten 
Issue is definitely with the signing of `Microsoft.Xaml.Behaviors.dll`.
I am able to reproduce this issue in sample .NET Core console app. 

Content of .NET console app:
```
using Microsoft.Xaml.Behaviors;
using System;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            Interaction.ShouldRunInDesignMode = true;
            Console.WriteLine("Hello World!");
            Console.ReadLine();
        }
    }
}
```

This .NET core console app is targeting to netcoreapp3.0
Closing this issue as the issue is reproable in console app as well and thus nothing to do with test framework.

**Closed by abhishkk** 2019-01-08 09:33 UTC
Labels: question
