### ISSUE TITLE
Cannot execute tests when DisableAppDomain is true

### ISSUE THREAD

**Issue by avivanoff** [microsoft/testfx#1598] opened 2023-02-18 19:03 UTC
## Describe the bug

An exception occurred while invoking executor 'executor://mstestadapter/v2': Could not load file or assembly

## Steps To Reproduce

Steps are the same as in #1493.

The problem happens with both 3.0.2 and 4.0.0-preview-20221222-4.
Unfortunately, this time I cannot create a simple project to re-create the problem, but it is reproducible on our pipelines. One thing I noticed Fusion is showing `Microsoft.TestPlatform.CoreUtilities` is being loaded from test adapter path instead of `vstest.console.exe` location. Settings `DisableAppDomain` to false fixes the problem.

The log:

```
An exception occurred while invoking executor 'executor://mstestadapter/v2': Could not load file or assembly 'Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.resources, Version=14.0.0.0, Culture=en-US, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
Stack trace:
Server stack trace: 
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly(String name, CultureInfo culture, Version version, Boolean throwOnFileNotFound, StackCrawlMark& stackMark)
   at System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly(CultureInfo lookForCulture, StackCrawlMark& stackMark)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Resource.get_MissingDeploymentDependency()
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Deployment.AssemblyLoadWorker.GetDependentAssembliesInternal(String assemblyString, IList`1 result, ISet`1 visitedAssemblies, IList`1 warnings)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Deployment.AssemblyLoadWorker.ProcessChildren(Assembly assembly, IList`1 result, ISet`1 visitedAssemblies, IList`1 warnings)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Deployment.AssemblyLoadWorker.GetDependentAssembliesInternal(String assemblyString, IList`1 result, ISet`1 visitedAssemblies, IList`1 warnings)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Deployment.AssemblyLoadWorker.ProcessChildren(Assembly assembly, IList`1 result, ISet`1 visitedAssemblies, IList`1 warnings)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Deployment.AssemblyLoadWorker.GetDependentAssembliesInternal(String assemblyString, IList`1 result, ISet`1 visitedAssemblies, IList`1 warnings)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Deployment.AssemblyLoadWorker.ProcessChildren(Assembly assembly, IList`1 result, ISet`1 visitedAssemblies, IList`1 warnings)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Deployment.AssemblyLoadWorker.GetFullPathToDependentAssemblies(String assemblyPath, IList`1& warnings)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Deployment.AssemblyLoadWorker.GetFullPathToDependentAssemblies(String assemblyPath, IList`1& warnings)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Utilities.AssemblyUtility.GetFullPathToDependentAssemblies(String assemblyPath, String configFile, IList`1& warnings)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Utilities.DeploymentUtility.AddDependencies(String testSource, String configFile, IList`1 deploymentItems, IList`1 warnings)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Utilities.DeploymentUtility.AddDependenciesOfDeploymentItem(String deploymentItemFile, IList`1 filesToDeploy, IList`1 warnings)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Utilities.DeploymentUtilityBase.Deploy(IList`1 deploymentItems, String testSource, String deploymentDirectory, String resultsDirectory)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Utilities.DeploymentUtilityBase.Deploy(String source, IRunContext runContext, ITestExecutionRecorder testExecutionRecorder, IList`1 deploymentItems, TestRunDirectories runDirectories)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.TestDeployment.Deploy(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestExecutionManager.RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle, TestRunCancellationToken cancellationToken)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.MSTestExecutor.RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.RunTestsWithSources.InvokeExecutor(LazyExtension`2 executor, Tuple`2 executorUriExtensionTuple, RunContext runContext, IFrameworkHandle frameworkHandle)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.<>c__DisplayClass46_0.<RunTestInternalWithExecutors>b__0()
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformThread.<>c__DisplayClass0_0.<Run>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformThread.Run(Action action, PlatformApartmentState apartmentState, Boolean waitForCompletion)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.TryToRunInStaThread(Action action, Boolean waitForCompletion)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.RunTestInternalWithExecutors(IEnumerable`1 executorUriExtensionMap, Int64 totalTests)
Inner exception: Could not load file or assembly 'Microsoft.TestPlatform.CoreUtilities, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
Stack trace:
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.AssemblyResolver.<>c__DisplayClass25_0.<OnResolveInternal>b__0()
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.AssemblyResolver.SafeLog(String assemblyName, Action loggerAction)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.AssemblyResolver.OnResolveInternal(Object senderAppDomain, ResolveEventArgs args, Boolean isReflectionOnly)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.AssemblyResolver.OnResolve(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
```

[AB#1827543](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1827543)

**Comment by engyebrahim** [comment] 2023-02-23 12:04
Hi @avivanoff,
I tried to reproduce the issue I added .runsettings file with app domain setting to true but the tests run without errors (I attached a picture) so please I need a sample project to reproduce the issue.
<img width="1550" alt="rr" src="https://user-images.githubusercontent.com/24208132/220900067-0fc2f842-fba6-45e3-9d83-738e1f7f29a5.png">

**Comment by engyebrahim** [comment] 2023-02-23 13:23
Hi @avivanoff,
I tried to reproduce the issue I added .runsettings file with app domain setting to true but the tests run without errors (I attached a picture) so please I need a sample project to reproduce the issue.
<img width="1477" alt="rr" src="https://user-images.githubusercontent.com/24208132/220919245-6f9eb5db-a9dc-48cc-8452-ca4e43049f19.png">

**Comment by avivanoff** [comment] 2023-02-23 15:21
@engyebrahim, as I said, I could not create a sample project, even though I tried using the exact same settings of our failing one. How can we proceed? Is there a way to produce a detailed log a can send to you?

**Comment by Evangelink** [comment] 2023-02-28 09:39
Hi @avivanoff,

Could you please follow the steps described here https://github.com/microsoft/vstest/blob/main/docs/troubleshooting.md#visual-studio and share the logs with us? It should produce some logs (probably better to clean the folder then run your tests to have the issue).

**Comment by avivanoff** [comment] 2023-03-01 04:41
@Evangelink, I got the logs. I did not remove any possibly sensitive information, so where can I send them?

**Comment by Evangelink** [comment] 2023-03-01 08:27
You can send them to my email amauryleve[at]microsoft[dot]com

**Comment by avivanoff** [comment] 2023-03-01 17:38
@Evangelink, logs are sent. Let me know if this is enough.

**Comment by Haplois** [comment] 2023-03-03 14:23
This might be because of multiple test projects (with different targets / or adapter versions) deploying to same directory.

**Comment by avivanoff** [comment] 2023-03-04 06:49
@Haplois, we use Central Package Management, so all adapters are the same version.

**Comment by Haplois** [comment] 2023-03-04 07:16
@avivanoff - if you provide a small repro, it would be much easier to debug. 

Even if you're using the same version of the adapters in all your test projects, if you output all your tests in same directory and they are in different TFNs, that might cause this issue. I'm sure after reviewing the logs @Evangelink will know more.

**Comment by avivanoff** [comment] 2023-03-04 07:25
@Haplois, I did mention in the original description that I was not able to create a sample project with repro this time. I also mentioned that assembly in question is being loaded from the wrong location - test adapter path instead of test host executable path.
All projects target .NET Framework 4.8 AnyCPU.

**Comment by Haplois** [comment] 2023-03-04 07:31
Sorry I read issue around 2am, missed that part. If you send your logs to me I can check the issue, but I'm no longer affiliated with Microsoft. My Twitter DMs are open. (https://twitter.com/medenibaykal)

**Comment by MarcoRossignoli** [comment] 2023-03-07 12:03
> Unfortunately, this time I cannot create a simple project to re-create the problem, but it is reproducible on our pipelines

@avivanoff are you able to provide your CI setup? How are you running tests? Are you using Azure DevOps, is so which agent version?

**Comment by avivanoff** [comment] 2023-03-11 20:41
- Azure DevOps, self-hosted pipeline agents 2.217.2, x64.
- Command line from the run logs:
```
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe "@C:\BuildAgent\_work\_temp\gaojnzzbvkw.tmp"
2023-03-10T19:21:15.3629877Z Microsoft (R) Test Execution Command Line Tool Version 17.5.0 (x64)
2023-03-10T19:21:15.3631012Z Copyright (c) Microsoft Corporation.  All rights reserved.
2023-03-10T19:21:15.4479151Z vstest.console.exe "C:\BuildAgent\_work\5\b\x64\Release\<test assembly 01>.dll"
2023-03-10T19:21:15.4480338Z "C:\BuildAgent\_work\5\b\x64\Release\<test assembly 02>.dll"
2023-03-10T19:21:15.4481065Z "C:\BuildAgent\_work\5\b\x64\Release\<test assembly 03>.dll"
2023-03-10T19:21:15.4481785Z "C:\BuildAgent\_work\5\b\x64\Release\<test assembly 04>.dll"
2023-03-10T19:21:15.4482441Z "C:\BuildAgent\_work\5\b\x64\Release\<test assembly 05>.dll"
2023-03-10T19:21:15.4483149Z "C:\BuildAgent\_work\5\b\x64\Release\<test assembly 06>.dll"
2023-03-10T19:21:15.4483879Z "C:\BuildAgent\_work\5\b\x64\Release\<test assembly 07>.dll"
2023-03-10T19:21:15.4486428Z "C:\BuildAgent\_work\5\b\x64\Release\<test assembly 08>.dll"
2023-03-10T19:21:15.4487145Z "C:\BuildAgent\_work\5\b\x64\Release\<test assembly 09>.dll"
2023-03-10T19:21:15.4487887Z "C:\BuildAgent\_work\5\b\x64\Release\<test assembly 10>.dll"
2023-03-10T19:21:15.4488611Z "C:\BuildAgent\_work\5\b\x64\Release\<test assembly 11>.dll"
2023-03-10T19:21:15.4489976Z "C:\BuildAgent\_work\5\b\x64\Release\<test assembly 12>.dll"
2023-03-10T19:21:15.4490664Z "C:\BuildAgent\_work\5\b\x64\Release\<test assembly 13>.dll"
2023-03-10T19:21:15.4491421Z "C:\BuildAgent\_work\5\b\x64\Release\<test assembly 14>.dll"
2023-03-10T19:21:15.4492049Z /TestCaseFilter:"TestCategory=CI"
2023-03-10T19:21:15.4492717Z /Settings:"C:\BuildAgent\_work\_temp\c5ogfs2xb5w.tmp.runsettings"
2023-03-10T19:21:15.4493284Z /Logger:"trx"
2023-03-10T19:21:15.4493972Z /TestAdapterPath:"C:\BuildAgent\_work\5\b\x64\Release"
```
- Run settings as reported in the run logs:
```
<RunSettings>
  <RunConfiguration>
    <DisableAppDomain>true</DisableAppDomain> <!--// DEPRECATED: remove when updating to MSTest 4, see https://github.com/microsoft/testfx/issues/1285.-->
    <MaxCpuCount>0</MaxCpuCount>
    <TargetPlatform>x64</TargetPlatform>
    <BatchSize>1000</BatchSize>
    <ResultsDirectory>C:\BuildAgent\_work\_temp\TestResults</ResultsDirectory>
  </RunConfiguration>
  <MSTest>
    <MapInconclusiveToFailed>true</MapInconclusiveToFailed>
    <CaptureTraceOutput>true</CaptureTraceOutput>
    <DeleteDeploymentDirectoryAfterTestRunIsComplete>false</DeleteDeploymentDirectoryAfterTestRunIsComplete>
    <DeploymentEnabled>true</DeploymentEnabled>
    <Parallelize>
      <Workers>0</Workers>
      <Scope>MethodLevel</Scope>
    </Parallelize>
  </MSTest>
  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="blame" enabled="True">
        <Configuration>
          <ResultsDirectory>C:\BuildAgent\_work\_temp\TestResults</ResultsDirectory>
          <CollectDump />
          <CollectDump />
        </Configuration>
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
  <LoggerRunSettings>
    <Loggers>
      <Logger friendlyName="blame" enabled="True" />
    </Loggers>
  </LoggerRunSettings>
</RunSettings>
```
@MarcoRossignoli, any other information I can provide to help you figure out the issue?

**Comment by avivanoff** [comment] 2023-03-13 12:21
The problem exists on both VM-based interactive and Docker-based pipeline agents.

Yes, it is VSTest@2 task. But I can also reproduce the issue by manually running the tests.

**Comment by avivanoff** [comment] 2023-03-20 18:11
@Evangelink, @MarcoRossignoli, any updates?

**Comment by MarcoRossignoli** [comment] 2023-03-22 06:44
Hi @avivanoff sorry for the late answer, we're working on the repro, no new updates so far.

**Comment by avivanoff** [comment] 2023-04-10 15:31
@MarcoRossignoli, anything? Anything I can do to provide more info?

**Comment by avivanoff** [comment] 2023-04-11 16:41
@Evangelink, @MarcoRossignoli, as more and more of our pipelines start failing, I was finally able to create a simple sample project [TestProject.zip](https://github.com/microsoft/testfx/files/11202832/TestProject.zip).

1. Extract to some folder.
2. Open command line and navigate to that folder.
3. Build:
`"c:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\MSBuild.exe" /t:Restore;Build TestProject.sln`
4. Run tests:
`"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" "bin\Debug\net48\TestProject1.dll" "bin\Debug\net48\TestProject2.dll" /Settings:"local.runsettings" /TestAdapterPath:"bin\Debug\net48"`
5. Observe the failure.

**Comment by MarcoRossignoli** [comment] 2023-04-12 06:54
Can you try to cleanup all bin/obj and bump the version to

```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.5.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.0.2" />
    <PackageReference Include="MSTest.TestFramework" Version="3.0.2" />
  </ItemGroup>
```
I've been able to run it in my local
```
Starting test execution, please wait...
A total of 2 test files matched the specified pattern.
MSTest Executor: Test Parallelization enabled for ...\TestProject\TestProject\TestResults\Deploy_mrossignoli 20230412T085307\Out\TestProject2.dll (Workers: 16, Scope: MethodLevel).
MSTest Executor: Test Parallelization enabled for ...\TestProject\TestProject\TestResults\Deploy_mrossignoli 20230412T085307\Out\TestProject1.dll (Workers: 16, Scope: MethodLevel).
  Passed TestMethod1 [4 ms]
  Passed TestMethod1 [3 ms]

Test Run Successful.
Total tests: 2
     Passed: 2
 Total time: 2.0651 Seconds
```

**Comment by avivanoff** [comment] 2023-04-13 19:48
That worked. Not sure how I missed these.

But the problem still exists on our build servers. Not sure what to do.

**Comment by Evangelink** [comment] 2023-04-14 08:34
Just to confirm that when running tests locally with the exact same solution/setup the tests are ok but on CI they are failing, right?

If that's the case, that would seem to indicate that there is some difference of setup between the local and the CI.

There is one thing that is puzzling me though. In your first comment you are saying that `DisableAppDomain=true` causes an issue while `DisableAppDomain=false` doesn't. The error stack trace is showing calls to `System.Runtime.Remoting.Proxies.RealProxy`, which would happen through AppDomain marshalling which indicates that the app domains are not disabled.

Would it be possible for us to have access to your real solution setup? I will ask my manager to see if we have some kind of private support path.

**Comment by avivanoff** [comment] 2023-04-16 17:14
@Evangelink,

- I can reproduce the issue locally.
- I should be able to send you the content of the bin folder.

**Comment by avivanoff** [comment] 2023-05-09 18:50
@Evangelink, any updates?

**Comment by Evangelink** [comment] 2023-05-12 08:44
Hi @avivanoff,

Sorry for the delay. We weren't able to reproduce the issue in any way. 

If you can always reproduce the issue, the easiest would be to have access to the repro (or the source code or dll). You can either send them here, by email to me (amauryleve[at]microsoft[dot]com) or use https://developercommunity.visualstudio.com/home where you can upload privately items.

**Comment by avivanoff** [comment] 2023-05-13 21:53
@Evangelink, I prepared an archive with the binaries required to reproduce the issue. It is 383MB, so email is out of question. Also, it is not clear to me how to privately upload this archive to you at https://developercommunity.visualstudio.com/home.

**Comment by Evangelink** [comment] 2023-05-15 16:47
Thanks @avivanoff! I will be looking at it this week and will let you know what I found.

**Comment by Evangelink** [comment] 2023-05-17 13:50
Hi @avivanoff! 

I don't yet have a fix but I was managed to make some good progresses on the error. Basically, there are 2 configurations from the runsettings that seems to be leading to this issue.

1. If you enable app domains (either set `DisableAppDomain` to `false` or remove the entry in the runsettings file), you will see that the error goes away and instead you have some warnings (stripped to minimal + redacted):

```csharp
Test Run deployment issue: an error occurred while getting satellite assemblies for deployment item '<redacted>.dll' (output directory 'x64'): System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
Parameter name: startIndex
Test Run deployment issue: an error occurred while getting satellite assemblies for deployment item '<redacted>.dll': System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
Parameter name: startIndex
Test Run deployment issue: Failed to get the file for deployment item '<redacted>.dll' (output directory 'x64'): System.IO.FileNotFoundException: Could not find file '<redacted>.dll'.
```

2. If you disable the `DeploymentEnabled` entry of the runsettings, you will now have your tests running.

Now that reminds me of this issue I fixed as part of the `3.0.2` release https://github.com/microsoft/testfx/pull/1502 and was exactly happening when the deployment mode was enabled.

I am now trying to have a precise idea of what is loaded or not to see what is causing this issue. I will keep you posted with my findings.

**Comment by Evangelink** [comment] 2023-05-17 17:15
@avivanoff I managed to find a fix that seems to be resolving the issue (at least from what I can see with the binaries). Would you mind beta testing a package I would send you to confirm this is fixing your issue?

**Comment by avivanoff** [comment] 2023-05-17 20:38
@Evangelink, of course. Just give me the test package info.

**Comment by Evangelink** [comment] 2023-05-18 14:39
@avivanoff I have sent you an email. Please confirm you received it and let me know if it fixed your issue or not.

**Comment by avivanoff** [comment] 2023-05-18 14:53
@Evangelink, sorry, nothing in my inbox or spam folder.

**Comment by Evangelink** [comment] 2023-05-18 14:57
Just sent again. In case you don't receive it, I will share a temp link here.

**Comment by avivanoff** [comment] 2023-05-18 16:00
@Evangelink, I got the email, but there are no attachments or anything else that points to the preview packages.

**Comment by Evangelink** [comment] 2023-05-18 16:03
Maybe our antivirus is doing some cleanup. Let me past link here https://microsofteur-my.sharepoint.com/:f:/g/personal/amauryleve_microsoft_com/ErR5Psya9zdIvswGBPW5G8wBH67ZE_arEHFu6BLxrAeEhg?e=uBJsOi

**Comment by avivanoff** [comment] 2023-05-18 17:35
@Evangelink, it worked.

**Comment by Evangelink** [comment] 2023-05-18 17:38
AWESOME! Thank you so much for your patience, I will merge the related PR and we will do the release next week.

**Comment by avivanoff** [comment] 2023-05-24 11:47
@Evangelink, any ETA?

**Comment by Evangelink** [comment] 2023-05-25 08:28
@avivanoff, release is now done. Please let us know if there is any other problem!

**Comment by avivanoff** [comment] 2023-05-25 15:48
@Evangelink, unfortunately, the problem is still there. I am trying to see where my verification went wrong.

Did you try 3.0.3 with the sample binaries I sent you?

**Comment by Evangelink** [comment] 2023-05-25 16:05
@avivanoff, No I haven't tried again as you confirmed the preview package was correct. I am testing now...

**Comment by avivanoff** [comment] 2023-05-25 19:59
@Evangelink, I attached another set of files to reproduce the issue to https://developercommunity.visualstudio.com/t/Cannot-execute-tests-when-DisableAppDoma/10363055.

These are some of my findings:

- If DisableAppDomain is true and there are deployment items, only the unit test assembly and deployment items are copied to "TestResults\Deploy_XXX\Out". Execution fails.
- If DisableAppDomain is false and there are deployment items, the unit test assembly, all dependencies and deployment items are copied to "TestResults\Deploy_XXX\Out". Execution succeeds.

In both cases the unit test assembly is loaded from TestResults\Deploy_XXX\Out, while in the first case dependencies are loaded from Bin folder, and in the second case they are loaded from TestResults\Deploy_XXX\Out.

**Comment by avivanoff** [comment] 2023-05-29 21:44
@Evangelink, the tests always worked because they were executing in app domains. It is when I disabled the app domain the tests started to fail.

**Comment by Evangelink** [comment] 2023-05-30 04:21
Thanks for the confirmation! Looks like this bug has always been present (when AppDomains are disabled). I will do another round of tests to be sure I didn't miss anything using your 2 samples and then will proceed with the new release either today or tomorrow

**Comment by avivanoff** [comment] 2023-05-31 14:08
@Evangelink, any updates on testing and 3.0.4 ETA?

**Comment by Evangelink** [comment] 2023-05-31 14:18
cc @engyebrahim who is handling this release.

**Comment by avivanoff** [comment] 2023-06-03 17:24
@Evangelink, @engyebrahim, so far the all test runs that used to fail now are succeeding. Thank you.

**Comment by Evangelink** [comment] 2023-06-05 07:26
@avivanoff Glad to hear! Thank you for your patience and for using MSTest.

**Closed by Evangelink** 2023-06-05 07:26 UTC
Labels: Type: Bug, sprint
