### ISSUE TITLE
TestAdapter 3.7 does not work with multiple TargetFrameworks

### ISSUE THREAD

**Issue by frobijn** [microsoft/testfx#4448] opened 2024-12-25 12:34 UTC
## Describe the bug

I've got a class library project and a MSTest project that both have `<TargetFrameworks>net8.0;net472</TargetFrameworks>`. With MSTest.TestAdapter 3.6.4 (in the latest VS2022) two sets of unit tests are shown in the Test Explorer, one for each target framework, and tests from both sets can be selected and run.

After upgrading to 3.7.0 the net472 tests are no longer discovered. The test output states:
```
No test is available in ...\net472\mytestassembly.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
```

## Steps To Reproduce

[MSTestAdapter_364](https://github.com/frobijn/bug_reports/tree/MSTestAdapter_364) - Example test project with MSTest.TestAdapter 3.6.4. The test can be run for both net472 and net8.0

[MSTestAdapter_370](https://github.com/frobijn/bug_reports/tree/MSTestAdapter_370) - Same project after "upgrading" to MSTest.TestAdapter 3.7. The net472 tests cannot be run anymore.

**Comment by Youssef1313** [comment] 2024-12-25 13:00
Thanks for reporting this @frobijn.

This looks like a duplicate of https://github.com/microsoft/testfx/issues/4426. I will go ahead and close. Meanwhile, you can subscribe to notifications on #4426.

**Closed by Youssef1313** 2024-12-25 12:59 UTC
Labels: Needs: Triage :mag:
