### ISSUE TITLE
IsInstanceOfType fails on COM-objects

### ISSUE THREAD

**Issue by HardCode4All** [microsoft/testfx#621] opened 2019-06-18 08:03 UTC
I was using the Microsoft.VisualStudio.QualityTools.UnitTestFramework in Visual Studio 2015 so far. 

Here is a TestMethod that worked until now:
   ```
 <TestMethod> Public Sub GetStringParameterTest()
        Dim rootParamSet As ParameterSet = XXXUtilities.GetOrCreateRootParameterSet(_workDocument, ROOT_PARAM_SET_NAME)
        Dim paramSubSet As ParameterSet = XXXUtilities.GetOrCreateParameterSubSet(rootParamSet, PARAM_SUBSET_NAME, False)
        Dim stringParameter As StrParam = XXXUtilities.GetOrCreateStringParameter(paramSubSet, "UNITTEST_STRING_PARAM", False)

        Dim actual As StrParam = XXXUtilities.GetStringParameter(paramSubSet, "UNITTEST_STRING_PARAM")

        Assert.IsNotNull(actual)
        Assert.IsInstanceOfType(actual, GetType(StrParam))
        Dim name As String = XXXUtilities.GetParameterShortName(actual.Name)
        Assert.AreEqual("UNITTEST_STRING_PARAM", name)
    End Sub
```
Expected behaviour: Assert.IsInstanceOfType(actual, GetType(StrParam)) returns true. StrParam is a Type defined in a COM-DLL. 

Today, I tried to use the Microsoft.VisualStudio.TestPlatform.TestFramework instead, because I need to use data-driven TestMethods with DataRows. 

Actual behavior: the same test now fails with this error:

> Result Message:	Assert.IsInstanceOfType failed.  Expected type:<KnowledgewareTypeLib.StrParam>. Actual type:<System.__ComObject>.

Obviously, the type StrParam was lost in favor of the completely generic System.ComObject. This feels like a regression compared to the "old" behaviour.

What am I missing here?

**Comment by cltshivash** [comment] 2019-06-19 06:50
@HardCode4All The thread apartment state is the same between the two versions. Is there a repro project that can be shared  ?

**Comment by HardCode4All** [comment] 2019-06-20 04:46
Unfortunately no, as the COM DLLs in question are intellectual property, but I will try to create a DLL that behaves alike which I can then share publicly. This might take a while, so please give me some time...

**Comment by HardCode4All** [comment] 2019-06-21 12:45
Okay, this is a bit more complex, I guess. I tried to quickly write a little COM-DLL that could reproduce the error, but I am afraid I cannot do that. Let me break that down:

The DLL in question is a very old, unmanaged code C++ DLL that is registered in Windows through regsvr32.exe. This DLL provides Interfaces (StrParam in the code above), which are in turn used by other projects and UnitTests.

As far as I understand it, in today's world of managed .NET code, you _cannot_ write such a DLL any longer, so I am not able to provide a corresponding project :( and I have no clue where to get an adequate (open-source) DLL to reproduce the behavior.

So I guess I will have to live with the old testing framework a bit longer. Anyway, thanks for the reply.

**Comment by cltshivash** [comment] 2019-06-24 00:38
@HardCode4All Did you try casting the instance returned to the type expected (StrParam) ? What is the signature of this function  XXXUtilities.GetStringParameter. Is it defined to return StrParam ?

**Comment by HardCode4All** [comment] 2019-06-25 17:52
Hmmm..... I wanted to test that, but when I now use Microsoft.VisualStudio.TestPlatform.TestFramework instead of Microsoft.VisualStudio.QualityTools.UnitTestFramework, it does not recognize any tests at all :( The "Test Explorer" shows no tests any longer. It just says "Build your solution to discover all available tests", but building the solution seems no to detect any tests. All test-methods are marked with the TestMethod-attribute, all Test-Classes are marked with the TestClass attribute.

 I tried to uninstall and reinstall the Framework, but to no avail. Am I missing something?

**Comment by cltshivash** [comment] 2019-06-26 06:05
Looks like test discovery is failing. Can you try the below ? This would give logs that can help us see to know more about the failure.https://github.com/microsoft/vstest-docs/blob/master/docs/diagnose.md 

vstest.console.exe <testassembly> /diag:log.txt

**Comment by HardCode4All** [comment] 2019-06-26 08:25
Thanks for this idea. Here is the logfile:

[log.txt](https://github.com/microsoft/testfx/files/3329021/log.txt)

**Comment by cltshivash** [comment] 2019-06-26 09:14
@HardCode4All  Please ensure you have added the below two nuget packages to your test project
"MSTest.TestAdapter", "MSTest.TestFramework"

**Comment by HardCode4All** [comment] 2019-06-26 09:48
They are both installed, yet the log-file stays the same :(

![Screenshot-_20190626_11-46-19](https://user-images.githubusercontent.com/38424724/60170193-45d10f80-9808-11e9-8020-56f2b6abec79.png)

[log2.txt](https://github.com/microsoft/testfx/files/3329406/log2.txt)

**Comment by mayankbansal018** [comment] 2019-07-05 11:25
The log file says, that the Mstest V2 adapter was not used to run the tests. Can you please pass `/InIsolation` flag, & share those diagnostics files as well.

Also after compiling can you check whether mstest*.dll were present along with your test dlls?

**Comment by HardCode4All** [comment] 2019-07-05 13:18
Thanks for that! I am on holiday at the moment but will try that as soon as I am back (July 15th).

**Comment by HardCode4All** [comment] 2019-07-19 13:30
Sorry for the long delay, here I am again. When  I add both packages to VS and try to run the Unit-Tests, I still get the message "Build your selection to discover all available tests". Building the solution doesn't help, so no news there.

When I take a look into the bin/Debug folder, I see 
Microsoft.VisualStudio.TestPlatform.TestFramework.dll
Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.dll
Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.xml
Microsoft.VisualStudio.TestPlatform.TestFramework.xml

and also the XML and DLL files for the solution (let's call then XXXUnitTests.xml and XXXUnitTests.dll). This file contains all the Unit-Tests of my solution, so they actually were detected somehow. Still, when I run the tests, I get the message "No tests available" :(

So I ran this command:

"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" E:\projekte\XXX\XXX\git\workspace\XXXUnitTests\bin\Debug\XXXUnitTests.dll /diag:c:\temp\log.txt /InIsolation

but it said:

Starting test execution, please wait...
Warning: No test is available in E:\projekte\XXX\XXX\git\workspace\XXXUnitTests\bin\Debug\XXXUnitTests.dll. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.

Information: Additionally, you can try specifying '/UseVsixExtensions' command if the test discoverer & executor is installed on the machine as vsix extensions and your installation supports vsix extensions. Example: vstest.console.exe myTests.dll /UseVsixExtensions:true
and here is the logfile:

[log.txt](https://github.com/microsoft/testfx/files/3411245/log.txt)

This time, the logfile is even shorter and does not look as if anything ran at all :(

**Comment by singhsarab** [comment] 2019-07-23 14:45
@HardCode4All 
The dlls that are interesting are following:
"Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter"
"Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices"
"Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface"

Aren't these present in the directory?

**Comment by singhsarab** [comment] 2019-07-29 11:47
@HardCode4All Gentle ping!

**Comment by HardCode4All** [comment] 2019-07-30 07:38
Hi singhsarab, sorry for the long delays, I have a weird time-schedule at the moment and can only look into this every 14 days.

Yes, all these DLLs are available in the project directory:
Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.dll
Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.dll
Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.Interface.dll
Microsoft.VisualStudio.TestPlatform.TestFramework.dll
Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.dll

And I can run all the tests in VS2015 without a problem, but when I try to run them via commandline, I still get:
`No test is available in E:\projekte\XXX\XXX\git\workspace\XXXUnitTests\bin\Debug\XXXUnitTests.dll`

Of course, when running from VS2015, the original problem still exists: 

> Test Name:	CreateStringParameterTest
> Test FullName:	XXXUnitTests.CATIAUtilitiesTests.CreateStringParameterTest
> Test Source:	E:\projekte\XXX\XXX\git\workspace\XXXUnitTests\XXXUtilitiesTests.vb : line 602
> Test Outcome:	Failed
> Test Duration:	0:00:00,1120243
> Result StackTrace:	at XXXUnitTests.XXXUtilitiesTests.CreateStringParameterTest() in E:\projekte\XXX\XXX\git\workspace\XXXUnitTests\XXXUtilitiesTests.vb:line 612
> **Result Message:	Assert.IsInstanceOfType failed.  Expected type:<KnowledgewareTypeLib.StrParam>. Actual type:<System.__ComObject>.**

The type `StrParam`, that works in the `Microsoft.VisualStudio.QualityTools.UnitTestFramework` is a generic `ComObject `in `Microsoft.VisualStudio.TestPlatform.TestFramework`. The method-signature is StrParam, and even a DirectCast didn't help.

**Comment by singhsarab** [comment] 2019-07-31 11:05
@HardCode4All 
I don't know why the adapter is not getting resolved for you when trying to run. The logs do not have any failures to load, it seems like we are missing something very basic.

And regarding the original issue, can you please share a sample project so that we can reproduce the issue?

**Comment by HardCode4All** [comment] 2019-08-02 06:41
> can you please share a sample project so that we can reproduce the issue?

That's the problem, you see. It's a confidential project with classes from an IP-protected CAD-solution, so no, I cannot share that :( I guess I will have to live with the old testing-framework, as that still works perfectly. The only reason I wanted to switch to TestFX was the possibility of parameterized test-methods, but I just wrote my own parameterized tests, so that's okay.

Thanks for your help anyway.

**Comment by singhsarab** [comment] 2019-08-05 05:59
I am glad that you are unblocked, but it's unfortunate that we were not able to resolve the issue for you. I am going ahead and closing this issue for now.
Please share a project if you'd still like to pursue.

**Closed by singhsarab** 2019-08-05 06:00 UTC
