### ISSUE TITLE
Can not create unit test project targeting .NET35 with mstestv2

### ISSUE THREAD

**Issue by Faizan2304** [Microsoft/testfx#269] opened 2017-09-13 07:02 UTC
## Description
> Can not create project targeting .NET35 with mstestv2

## Steps to reproduce
> Create a MStestv2 test project in visual studio 2017. (Visual C# -> Test)
> Re target project to .Net35 

## Expected behavior
> Re-Target should be get completed without any issue

## Actual behavior
> Its failing to do so. Migration report is as follows 
![image](https://user-images.githubusercontent.com/19184362/30363885-885315a4-987f-11e7-854b-fe49e2b9fefc.png)

**Comment by AbhitejJohn** [comment] 2017-09-14 10:37
Dupe of #196.

**Closed by AbhitejJohn** 2017-09-14 10:37 UTC
