### ISSUE TITLE
Improvement: ClassCleanup method to trigger after worker has executed all test methods not after all workers are complete

### ISSUE THREAD

**Issue by KitoCoding** [microsoft/testfx#580] opened 2019-03-12 19:35 UTC
When running multiple [TestClass]es at the same time, why does the [ClassCleanup()] methods only get called at the very end?

File: UnitTest1.cs

```
    [TestClass]
    public class UnitTest1
    {
        [ClassInitialize()]
        public static void ClassInit(TestContext context) { }
    
        [ClassCleanup()]
        public static void ClassCleanup() { }
    
        [TestMethod]
        public void TestMethod() { }
    }
```

File: UnitTest2.cs

```
    [TestClass]
    public class UnitTest2
    {
        [ClassInitialize()]
        public static void ClassInit(TestContext context) { }
    
        [ClassCleanup()]
        public static void ClassCleanup() { }
    
        [TestMethod]
        public void TestMethod() { }
    }
```

The execution order is the following:

 1. UnitTest2.ClassInit() 
 2. UnitTest2.TestMethod() 
 3. UnitTest1.ClassInit()
 4. UnitTest1.TestMethod()
 5. UnitTest2.ClassCleanup()
 6. UnitTest1.ClassCleanup()

Notice that both [ClassCleanup] methods are executed at the end of the set; not after each TestClass is "done".

But I expected a different behavior:

 1. UnitTest2.ClassInit()
 2. UnitTest2.TestMethod()
 3. UnitTest2.ClassCleanup() - Expected
 4. UnitTest1.ClassInit()
 5. UnitTest1.TestMethod()
 6. UnitTest1.ClassCleanup() - Expected

Microsoft's Documentation - ClassCleanupAttribute Class says, "Identifies a method that contains code to be used after **ALL** the tests in the test class have run and to free resources obtained by the test class."

But it appears to be run/executed late, after **ALL** tests have run.  This seems wrong, and it is blocking my development.

**Comment by cltshivash** [comment] 2019-03-15 05:46
Assembly and class initialize today run at the end today. Could you please elaborate on why this would block your development ?

**Comment by ShreyasRmsft** [comment] 2019-03-18 10:53
@KitoCoding any updates here?

**Comment by KitoCoding** [comment] 2019-03-20 13:07
once a class has run all of its test cases, there is no reason to not run the test class clean up method right away.  the test class is complete, so run the method... it may just be the way I imagining test cases, but it will make parallel tests much easier.

**Comment by KitoCoding** [comment] 2019-03-20 13:08
For example, lets say i have 50 test classes, and since msTest doesn't run test classes or methods in order, I have my first test method run and its the only method in the class. I have to wait for 50 test classes to complete running before I am able to run the test class clean up method.  Thats just silly

**Comment by cltshivash** [comment] 2019-03-20 13:42
@KitoCoding Are you dependent on the cleanup done in one test class in the cleanup/initialize of another test class ? What does your cleanup do ?

**Comment by cfletcher** [comment] 2019-05-13 15:55
@cltshivash In my use case we're running acceptance tests and our ClassCleanup is cleaning up test mocks. Cleaning them up earlier would reduce our chance of mock collisions and make debugging test issues easier (less concurrent mocks).
I wouldn't say it's blocking development for me, but it would be a valuable improvement. I realise we could just run that code outside of the cleanup segment, say in the ClassInitialize but its not init code its cleanup code

**Comment by vlaskal** [comment] 2019-05-28 17:09
Hi @cltshivash, 
I have to join to this request since I run into trouble when ClassInitialize method allocate limited resources. In my case it is Selenium WebDriver, which we have around 4 nodes with 5 workers. All tests are parallelized and execution scope is ClassLevel. When you run test then first 20 test classes are executed and the rest is not because the resources is not released and new cannot be taken. Test class holds instance and wait until all other test fails.
I think is good practice to release resources as soon as possible therefore ClassCleanup should be executed when all tests from test class are done. 
And also ClassCleanup should be executed in same thread as ClassInitialize and all test methods of the class. It is executed in different thread than tests right now.

**Comment by cltshivash** [comment] 2019-05-29 04:53
@vlaskal @cfletcher Thanks for the details. It helps provide the context. If one of you can contribute this change that would be great.

**Comment by vlaskal** [comment] 2019-05-30 06:40
@cltshivash I can try but also some advice would be good. I already look into the code and found a trouble with DoNoTParallelize attribute. I think even this test should be done between same ClassInitialize and ClassCleanup and maybe also on same thread. Right now it is executed after all parallel tests in project.
So are we able to describe somehow how it should work with DoNotParallelize attribute? 
Then it is possible to start implement this.

**Comment by pleonex** [comment] 2019-07-11 08:47
In my case this a blocking point for using MSTest. Our test classes create an HTTPListener for a specific port. Since `ClassCleanup` is not called after the tests of the class run, we cannot reuse the port between test classes (you cannot bind twice to the same port). We cannot use use different ports either because of Windows, it requires to allow binding to the port with `netsh`.

```
netsh http add urlacl url=http://+:<theport>/<url>/ user=DOMAIN\USER
```

This mean, that for every test class that we add, we need to use a new port so every developer needs to run again the `netsh` command for the new port.

In other project we have a similar issue because we use a third-party that it's binding in UDP/TCP ports, if it cannot bind in a port it tries within a range, but that range is no longer large enough because of the number of test classes we have.

I think that any project using networking will find this as a real issue, because we cannot release the resources between test classes.

**Comment by KitoCoding** [comment] 2019-07-30 13:17
I would just like to know the reasons as to why class clean up is triggered after all workers are complete. i understand if you are running parralelle runs at a method level. Sure, with no way for MSTest v2 to order the test cases, then it makes sense to just run after all workers are complete. But you supply the option to run at a test class level. One worker per test class. This is what we use, A worker should run the test init, all its methods then its clean up.

**Comment by KitoCoding** [comment] 2019-07-30 13:26
Implementing with DoNoTParallelize attribute might be tricky, if thats the case. A warning should go out to the user. "TestCleanUp cannot be triggered until all Workers are complete due to the DoNoTParallelize attribute found [insert location]."

If a worker is scheduled to run at a test class level and all its methods are good to go (does not have the DoNoTParallelize attribute) then trigger the class clean up. 

If a worker encounters a DoNoTParallelize attribute, then that worker cannot trigger test clean up until the very end. 

But my methods assume workers understand the order in which they are going to work, and they also are aware of other workers and their jobs. 

Essentially:

If a worker encounters a TestMethod with the DoNoTParallelize attribute, then do not trigger its TestClassClean up method until all workers are complete. Make sure to log warning so the user knows why its clean ups are not triggering

**Comment by KitoCoding** [comment] 2019-10-21 18:44
It is not documented because it is a bug. They have admitted that this isn't as designed but its a low priority.

**Comment by kfrajtak** [comment] 2019-10-22 06:01
Well, if there is a bug that completely changes the test life cycle I would expect it to be well documented.

**Comment by vlaskal** [comment] 2019-10-23 13:33
I would like to know what is expected behavior in following scenario. 
Let's imagine:
* 10 test classes each with several test methods and some of them are flagged by DoNotParallel attribute. At least one method in each class.
* Execution level is set to MethodLevel 
* Number of workers/threads is set to 5

**Comment by kfrajtak** [comment] 2019-10-25 07:31
I have also found that the test class constructor is invoked before each test.

**Comment by ScottMichaud** [comment] 2020-02-03 17:39
> Assembly and class cleanup today run at the end. Could you please elaborate on why this would block your development ?

It looks like the thread has already made some valid use cases, but here's another example: Using Appium.WebDriver to run integration tests on a single-instance application with non-trivial load and close.

I would expect that each TestClass could be used to launch the application into a specific state, run the unit tests on that state, then close the application. Because the ClassCleanup doesn't run before the next class attempts to start testing, the driver attempts to launch the application a second time in a different mode while the first instance is still open.

We're currently using TestInitialize and TestCleanup to allow a "Run All" to succeed, but this significantly limits our ability to break apart our integration tests into separate, well defined TestMethods due to how much execution time it adds.

Of course, initialization and clean-up at arbitrary levels of granularity (ex: groups) could help minimize execution time further, by batching tests to minimize state changes within an application run, but TestClasses would cover most of that need (by cutting out the load and shutdown cycle).

**Comment by RyanClementsHax** [comment] 2021-02-05 20:29
https://github.com/microsoft/testfx/issues/580#issuecomment-473166442
My team is also experiencing an issue with this design of when ClassCleanup is called. I figured I would contribute our use case for this thread. For us, we are developing database integration tests where each test class tests a partition of our database access code. We could force all of these tests to run sequentially, resetting the database after each test run, but this is extremely expensive. To allow for more parallelism and avoid having to reset so often, we want to create a test database for each one of these test classes. Creating one database per test class (thus per partition of our entire app) is too much. This lead us to a solution where we create a fixed set of databases these classes can use, reset after they are done, and release the database connection back to the pool for other test classes to use. With ClassCleanup happening after all other tests classes run, these test classes will never have the chance to release their resources for other test classes to use. As a result, the lack of this feature is keeping us from using this library even though we really love it and is familiar with everything else we do. Hope this helps.

**Comment by KitoCoding** [comment] 2021-03-19 17:41
Been open for a while, any update?

**Comment by BoMarley** [comment] 2021-04-29 12:26
any updates?

**Comment by ptrace** [comment] 2021-04-29 15:11
this would be very useful for me as well

**Comment by Michael-SEW** [comment] 2021-04-30 10:41
for me as well
it's been a while since now we are using a workaround for this issue.

**Comment by dibyamani** [comment] 2021-07-07 01:07
This is very helpful while working with database tests. Each ClassInitialize creates necessary tables, storedprocedures, feeding data and other necessary objects in sql server database and it should have provision to drop them withing the same classes's ClassCleanup. If we are not able to do so, another test class might be using the same object and it is failed.

**Comment by xuxiaotun** [comment] 2021-08-18 08:50
Is it the same reason why we can't map the classcleanup log to the last testmethod?

![image](https://user-images.githubusercontent.com/13480617/129868342-1d138ae8-9c87-466a-9c12-4d00bbdfbf1d.png)

**Comment by Haplois** [comment] 2021-11-23 18:41
This is fixed in https://github.com/microsoft/testfx/pull/968 and released with 2.2.8. To enable it you can set ClassCleanupBehavior to [ClassCleanupBehavior.EndOfClass][end-of-class] in your [ClassCleanup][class-cleanup] attribute.

 This can also be set on assembly level by [ClassCleanupExecution][class-cleanup-execution] assembly level attribute.

  [class-cleanup]: https://github.com/microsoft/testfx/blob/rel/2.2.8/src/TestFramework/MSTest.Core/Attributes/Lifecycle/Cleanup/ClassCleanupAttribute.cs
  [class-cleanup-execution]: https://github.com/microsoft/testfx/blob/rel/2.2.8/src/TestFramework/MSTest.Core/Attributes/Lifecycle/Cleanup/ClassCleanupExecutionAttribute.cs
  [end-of-class]: https://github.com/microsoft/testfx/blob/rel/2.2.8/src/TestFramework/MSTest.Core/Attributes/Lifecycle/Cleanup/ClassCleanupBehavior.cs

**Closed by Haplois** 2021-11-23 18:41 UTC
Labels: enhancement

**Comment by nir-boger** [comment] 2021-11-23 18:46
Thank you!

**Comment by sergiuciudin** [comment] 2022-01-12 21:26
Seems it's not working for me, anyone tried it?

**Comment by ailn** [comment] 2022-01-20 02:19
Didn't work for me as well

**Comment by nohwnd** [comment] 2022-01-20 06:08
Tried it again. Works fine for me. Did you specify the correct behavior to the attribute?

```
C:\t\mstest35> dotnet test; cat bin\Debug\net6.0\log.txt
  Determining projects to restore...
  Restored C:\t\mstest35\mstest35.csproj (in 481 ms).
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  mstest35 -> C:\t\mstest35\bin\Debug\net6.0\mstest35.dll
Test run for C:\t\mstest35\bin\Debug\net6.0\mstest35.dll (.NETCoreApp,Version=v6.0)
Microsoft (R) Test Execution Command Line Tool Version 17.2.0-preview-20211210-01
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:     2, Skipped:     0, Total:     2, Duration: 1 s - mstest35.dll (net6.0)
UnitTest1 start.
UnitTest1 done.
UnitTest2 start.
UnitTest2 done.
```

```csproj
<!-- file mstest35.csproj -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.11.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.2.8" />
    <PackageReference Include="MSTest.TestFramework" Version="2.2.8" />
    <PackageReference Include="coverlet.collector" Version="3.1.0" />
  </ItemGroup>

</Project>

```

```cs
// file UnitTest1.cs
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.IO;
using System.Threading;

[assembly: ClassCleanupExecution(ClassCleanupBehavior.EndOfClass)]

namespace mstest35;

public static class LogHelper
{
    public static void AppendLine(string text) => File.AppendAllText(
            Path.Combine(AppContext.BaseDirectory, "log.txt"),
            text + "\n");
}

[TestClass]
public class UnitTest1
{
    [ClassCleanup]
    public static void Cleanup()
    {
        LogHelper.AppendLine($"{nameof(UnitTest1)} done.");
    }

    [TestMethod]
    public void TestMethod1()
    {
        LogHelper.AppendLine($"{nameof(UnitTest1)} start.");
    }
}

[TestClass]
public class UnitTest2
{
    [ClassCleanup]
    public static void Cleanup()
    {
        LogHelper.AppendLine($"{nameof(UnitTest2)} done.");

    }

    [TestMethod]
    public void TestMethod1()
    {
        LogHelper.AppendLine($"{nameof(UnitTest2)} start.");
        Thread.Sleep(1000);
    }
}
```
