### ISSUE TITLE
MSTest 2.2.4+ does not runs tests contained in classes with non alphanumeric characters in the class name

### ISSUE THREAD

**Issue by sylvainouel** [microsoft/testfx#941] opened 2021-08-20 12:49 UTC
This works fine with MSTest.TestAdapter and MSTest.TestFramework 2.2.3, but the test is skipped with 2.2.4 or 2.2.5.

```
module x.TestProject1

open System
open Microsoft.VisualStudio.TestTools.UnitTesting

[<TestClass>]
type ``babette la morue`` () =

    [<TestMethod>]
    member this.TestMethodPassing () =
        Assert.IsTrue(true);
```
I get the following output from dotnet test:
```
PS C:\Users\souellet\source\repos\TestProject1> dotnet test
  Determining projects to restore...
  All projects are up-to-date for restore.
  TestProject1 -> C:\Users\souellet\source\repos\TestProject1\bin\Debug\net5.0\TestProject1.dll
Test run for C:\Users\souellet\source\repos\TestProject1\bin\Debug\net5.0\TestProject1.dll (.NETCoreApp,Version=v5.0)
Microsoft (R) Test Execution Command Line Tool Version 16.11.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Skipped TestMethodPassing

None     - Failed:     0, Passed:     0, Skipped:     0, Total:     0, Duration: 2 ms - TestProject1.dll (net5.0)
PS C:\Users\souellet\source\repos\TestProject1>
```

Visual Studio 16.11.1
dotnet --info says:

```
C:\Windows\System32>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.400
 Commit:    d61950f9bf

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.400\

Host (useful for support):
  Version: 5.0.9
  Commit:  208e377a53
```

**Comment by Evangelink** [comment] 2022-09-06 08:53
I can reproduce the issue. Looks like the space is causing issue.

**Comment by Evangelink** [comment] 2022-10-13 08:20
This is not linked to the test ID generation but was linked to a bug in hierarchy processing. Updating our object model dependency fixed the issue.

I will close the issue and confirm fix will be included in v3.

**Closed by Evangelink** 2022-10-13 08:20 UTC
Labels: bug, area-core
