### ISSUE TITLE
Extensibility: Custom assertions

### ISSUE THREAD

**Issue by pvlakshm** [Microsoft/testfx#138] opened 2017-04-07 09:41 UTC
## Description
Enable users to define custom assertions that plug-in to the test framework’s assertion infrastructure.
RFC: [Framework Extensibility for Custom Assertions](https://github.com/Microsoft/testfx-docs/blob/master/RFCs/002-Framework-Extensibility-Custom-Assertions.md)

**Comment by AbhitejJohn** [comment] 2017-04-09 19:47
Dupe of #116.

**Closed by AbhitejJohn** 2017-04-09 19:47 UTC
