### ISSUE TITLE
No 'AddResultFile' implementation in TestContext on .NET Core 2.0 test project

### ISSUE THREAD

**Issue by Aecid** [Microsoft/testfx#394] opened 2018-03-30 13:15 UTC
## Description
Using .Net Core 2.0 MSTest V2 project - I don't have access to some TestContext methods that are present on .Net Framework project.

## Steps to reproduce
Create a .Net Core 2.0 MSTest project. Add TestContext property to a Unit Test class. Try to add a file to a TestContext using [TestContext.AddResultFile()](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.testtools.unittesting.testcontext.addresultfile.aspx) method 

## Expected behavior
There should be such method in TestContext class

## Actual behavior
There is no such method in TestContext class

## Environment
MSTest V2  1.2.0
.Net Core 2.0

**Comment by ShreyasRmsft** [comment] 2018-04-04 10:09
hi @Aecid,
you are indeed right the implementation for AddResultFile is missing for the net standard implementation of the TestContext Abstract class.

Here is the[ full CLR implementation ](https://github.com/Microsoft/testfx/blob/b81c74730e11fc4cbe54d3b67752db13e7ce0491/src/Adapter/PlatformServices.Desktop/Services/DesktopTestContextImplementation.cs#L231)

Here is the [netstandard implementation](https://github.com/Microsoft/testfx/blob/b81c74730e11fc4cbe54d3b67752db13e7ce0491/src/Adapter/PlatformServices.Shared/netstandard1.0/Services/ns10TestContextImplementation.cs) that is missing this function

Please feel free to contribute. It's a very small fix and will mostly involve copying the same implementation and maybe adding a UnitTest or two.

**Comment by Aecid** [comment] 2018-04-06 08:36
Ok, I'll try to do this next week, thank you. :)

**Comment by ShreyasRmsft** [comment] 2018-08-23 05:48
@parrainc let me know if you need any help with the PR once you get started on it.

**Comment by parrainc** [comment] 2018-08-23 14:58
thanks @ShreyasRmsft 
I'm already working on it, will let you know if i get lost with the PR. :)

**Comment by parrainc** [comment] 2018-08-23 22:26
Hi @ShreyasRmsft 

I already implemented the **AddResultFile** method and **GetResultFiles** as well, created a couple of unit tests for both methods and pushed the commits to my repo. 

But, the implementation for **AddResultFile** is not the same as in the full CLR implementation you provided, given that apparently the netstandard version used in the Shared project is lower than 1.3 (which not contains **_Path.GetFullPath()_** method used to get the absolute path of the file name).

Please, kindly ask you to review [[the implementation I've done in my repo](https://github.com/parrainc/testfx/blob/issue394-addresultfile-impl/src/Adapter/PlatformServices.Shared/netstandard1.0/Services/ns10TestContextImplementation.cs#L154)] and suggests if there's a way to implement what **_Path.GetFullPath()_** method does in a netstandard version lower than 1.3.

I'm just missing that in order to make the PR for this issue :)

Thanks in advanced!!

**Comment by stilren** [comment] 2018-09-21 09:50
How would one add a result file to the test results while waiting for this feature?

**Comment by ShreyasRmsft** [comment] 2018-09-24 05:35
@pvlakshm @PBoraMSFT to answer when this will be picked up from our side.

**Comment by drewsac** [comment] 2018-11-28 16:17
Are there any workarounds or timeline for when this will be merged in?

**Comment by drewsac** [comment] 2018-12-04 21:10
Why can't the caller be responsible for providing the full path?

**Comment by parrainc** [comment] 2018-12-04 21:46
@drewsac 
> Are there any workarounds or timeline for when this will be merged in?

In order to implement this (merge it into master branch), PR #411 must be merged. We're still working on that one, which has a pretty good progress but there are a few things (mostly validations) that need to be done. 

> Why can't the caller be responsible for providing the full path?

My understanding, the caller of `.AddTestResultFile()` should be able to specify both the full path or a relative path, not just the full path. That way things are easier for them, and if have a file in the bin/Test Result folders doesn't need to specify the full path, just the filename.

In any case, if the responsibility of providing the absolute path is shift to the caller, then [the code](https://github.com/parrainc/testfx/blob/issue394-addresultfile-impl/src/Adapter/PlatformServices.Shared/netstandard1.0/Services/ns10TestContextImplementation.cs#L147) in my repo must work as it, instead of depending of `.GetFullPath()` method.

Sorry I can't provide you with a specific date on when this will be picked up. Let's wait until PR #411 got merged, and as soon as that happens I'll make sure to open the PR for this important change.

**Comment by chrimc62** [comment] 2019-04-15 23:36
Any progress on this?  It is a couple of months later and this is still an issue.

**Comment by jayaranigarg** [comment] 2019-04-23 10:45
@chrimc62 : Thank you for your patience. We have it planned for this quarter. Refer (https://github.com/Microsoft/testfx-docs/blob/master/Quarterly%20Checkins/QC-2019-Q1.md)

**Comment by jayaranigarg** [comment] 2019-04-24 06:57
@parrainc : We have added NetCoreTestContextImplementation seperately and NetCore Platform Service targets netstandard 1.5, so implementing this should be pretty straightforward now.
We would love to have a contribution for this. Let me know if you need any help on this.

**Comment by parrainc** [comment] 2019-04-25 00:36
Wonderful news, I haven't noticed that change until now. I'm pulling master into my branch and fixing this one. Thanks for the heads up @jayaranigarg

**Comment by jayaranigarg** [comment] 2019-04-29 06:23
Fixed as part of #609

**Closed by jayaranigarg** 2019-04-29 06:23 UTC
Labels: enhancement, up-for-grabs

**Comment by jayaranigarg** [comment] 2019-04-29 14:03
@bgoggan : Yes. It will be available. We haven't released the nuget packages with these changes yet. I can share early bits if you would want to try them out.

**Comment by bgoggan** [comment] 2019-04-29 14:07
Ok, that's no problem. Do you happen to have any timeline on when the nuget packages will be available? We're still working on upgrading all our test projects to core so it's not an immediate rush for me to implement.

**Comment by jayaranigarg** [comment] 2019-04-29 16:53
@bgoggan: We don't have a release planned as of now. We will definitely release one at the end of the quarter, checkout our [roadmap](https://github.com/Microsoft/testfx#roadmap). Early releases happens depending on need basis.

**Comment by bgoggan** [comment] 2019-04-29 16:58
Ok, sounds good. Thanks for the information. I may contact you again to take you up on your offer of sharing the early pieces if that's still ok with you. I'll just see how things progress on my end with everything else.

**Comment by bgoggan** [comment] 2019-04-30 11:32
Good morning @jayaranigarg: If possible, I'd like to take you up on your offer of sharing the early bits of the AddResultsFile changes to see if it's something I can temporarily handle until the official release. Just let me know. Thanks.

**Comment by jayaranigarg** [comment] 2019-04-30 12:53
@bgoggan : You can use our latest bits from here:
https://dotnet.myget.org/F/mstestv2/api/v3/index.json

In particular, you should update your adapter and framework nuget package to these versions:
https://dotnet.myget.org/feed/mstestv2/package/nuget/MSTest.TestAdapter/2.0.0-build-20190430-01
https://dotnet.myget.org/feed/mstestv2/package/nuget/MSTest.TestFramework/2.0.0-build-20190430-01

**Comment by bgoggan** [comment] 2019-04-30 14:12
@jayaranigarg: thank you. I'll give that a shot.

**Comment by jayaranigarg** [comment] 2019-04-30 14:28
Locking the thread as the issue is resolved from our end. Please feel free to create new issue if you need any help.
