### ISSUE TITLE
Extensiblity: Custom attributes

### ISSUE THREAD

**Issue by pvlakshm** [Microsoft/testfx#137] opened 2017-04-07 09:40 UTC
## Description
Enable users to define strongly typed description attributes as opposed to <string, string> key value pairs.
RFC: [Framework Extensibility Description Attributes](https://github.com/Microsoft/testfx-docs/blob/master/RFCs/001-Framework-Extensibility-Description-Attributes.md
)

**Comment by AbhitejJohn** [comment] 2017-04-09 19:45
Dupe of #116.

**Closed by AbhitejJohn** 2017-04-09 19:45 UTC
