### ISSUE TITLE
DataRow: number of attributes is limited after 3.0.0

### ISSUE THREAD

**Issue by DanMcNamee** [microsoft/testfx#1554] opened 2023-01-13 18:07 UTC
## Describe the bug
Prior to version 3.0.1, DataRow did not limit the number of Attributes, but starting with 3.0.1 forward, the number of Attributes is limited to 16.

## Steps To Reproduce
Create a test where you are providing data to a function with a DataRow with more than 16 Attributes.

        [DataTestMethod]
        [DataRow("73156", "TA_SuperUser1", "81000198", 2, 3, 4, 5, 6, 7, "8.00", "10.00", "5.00", "3.00", "2.00", "01/16/2023", "01/17/2023", "01/18/2023", "01/19/2023", "01/20/2023")]
        public void VerifyBumpUps(string employeeId, string userId, string jobCodeInput, int two, int three, int four, int five, int six, int seven, string eightHrs, string tenHrs, string fiveHrs, string threeHrs, string twoHrs, string mon, string tue, string wed, string thu, string fri)
        {
                ...code here
        }

## Expected behavior
Expecte behavior is for the code to compile and execute.

## Actual behavior
Starting with version 3.0.1, DataRow has a hard coded limit or 16 Attributes, so the compile fails with the following error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1729	'DataRowAttribute' does not contain a constructor that takes 19 arguments	WFMTests	C:\Users\DMcnamee\source\repos\WorkForceManagement\WFMTests\UI\TimeEntry\TimeEntry.cs	727	Active

## Additional context
Decompiled code shows hard coded DataRow constructors for up to 16 attributes, where before it the constructor would accept any number of Attributes.

Origial code:
#region Assembly Microsoft.VisualStudio.TestPlatform.TestFramework, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// C:\Users\DMcnamee\.nuget\packages\mstest.testframework\3.0.0\lib\net6.0\Microsoft.VisualStudio.TestPlatform.TestFramework.dll
// Decompiled with ICSharpCode.Decompiler 7.1.0.6543
#endregion

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Reflection;

namespace Microsoft.VisualStudio.TestTools.UnitTesting
{
    //
    // Summary:
    //     Attribute to define in-line data for a test method.
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    public class DataRowAttribute : Attribute, ITestDataSource
    {
        //
        // Summary:
        //     Gets data for calling test method.
        public object?[] Data { get; }

        //
        // Summary:
        //     Gets or sets display name in test results for customization.
        public string? DisplayName { get; set; }

        //
        // Summary:
        //     Initializes a new instance of the Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute
        //     class.
        //
        // Parameters:
        //   data:
        //     The data object.
        public DataRowAttribute(object? data)
        {
            Data = new object[1] { data };
        }

        //
        // Summary:
        //     Initializes a new instance of the Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute
        //     class which takes in an array of arguments.
        //
        // Parameters:
        //   data:
        //     More data.
        public DataRowAttribute(params object?[]? data)
        {
            Data = data ?? new object[1];
        }

        public IEnumerable<object?[]> GetData(MethodInfo methodInfo)
        {
            return new object[1][] { Data };
        }

        public virtual string? GetDisplayName(MethodInfo methodInfo, object?[]? data)
        {
            if (!string.IsNullOrWhiteSpace(DisplayName))
            {
                return DisplayName;
            }

            if (data != null)
            {
                return string.Format(CultureInfo.CurrentCulture, FrameworkMessages.DataDrivenResultDisplayName, methodInfo.Name, string.Join(",", data.AsEnumerable()));
            }

            return null;
        }
    }
}
#if false // Decompilation log
'236' items in cache
------------------
Resolve: 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Found single assembly: 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Load from: 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.13\ref\net6.0\System.Runtime.dll'
------------------
Resolve: 'System.Collections, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Found single assembly: 'System.Collections, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Load from: 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.13\ref\net6.0\System.Collections.dll'
------------------
Resolve: 'System.Text.RegularExpressions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Found single assembly: 'System.Text.RegularExpressions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Load from: 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.13\ref\net6.0\System.Text.RegularExpressions.dll'
------------------
Resolve: 'System.Linq, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Found single assembly: 'System.Linq, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Load from: 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.13\ref\net6.0\System.Linq.dll'
------------------
Resolve: 'System.Threading, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Found single assembly: 'System.Threading, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Load from: 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.13\ref\net6.0\System.Threading.dll'
#endif

New code with hard coded attributes:
#region Assembly Microsoft.VisualStudio.TestPlatform.TestFramework, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// C:\Users\DMcnamee\.nuget\packages\mstest.testframework\3.0.2\lib\net6.0\Microsoft.VisualStudio.TestPlatform.TestFramework.dll
// Decompiled with ICSharpCode.Decompiler 7.1.0.6543
#endregion

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Reflection;

namespace Microsoft.VisualStudio.TestTools.UnitTesting
{
    //
    // Summary:
    //     Attribute to define in-line data for a test method.
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    public class DataRowAttribute : Attribute, ITestDataSource
    {
        //
        // Summary:
        //     Gets data for calling test method.
        public object?[] Data { get; }

        //
        // Summary:
        //     Gets or sets display name in test results for customization.
        public string? DisplayName { get; set; }

        //
        // Summary:
        //     Initializes a new instance of the Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute
        //     class.
        public DataRowAttribute()
        {
            Data = Array.Empty<object>();
        }

        //
        // Summary:
        //     Initializes a new instance of the Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute
        //     class.
        //
        // Parameters:
        //   arg1:
        //     The first argument.
        public DataRowAttribute(object? arg1)
        {
            Data = new object[1] { arg1 };
        }

        //
        // Summary:
        //     Initializes a new instance of the Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute
        //     class which takes in an array of arguments.
        //
        // Parameters:
        //   arg1:
        //     The first argument.
        //
        //   arg2:
        //     The second argument.
        public DataRowAttribute(object? arg1, object? arg2)
        {
            Data = new object[2] { arg1, arg2 };
        }

        //
        // Summary:
        //     Initializes a new instance of the Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute
        //     class which takes in an array of arguments.
        //
        // Parameters:
        //   arg1:
        //     The first argument.
        //
        //   arg2:
        //     The second argument.
        //
        //   arg3:
        //     The third argument.
        public DataRowAttribute(object? arg1, object? arg2, object? arg3)
        {
            Data = new object[3] { arg1, arg2, arg3 };
        }

        //
        // Summary:
        //     Initializes a new instance of the Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute
        //     class which takes in an array of arguments.
        //
        // Parameters:
        //   arg1:
        //     The first argument.
        //
        //   arg2:
        //     The second argument.
        //
        //   arg3:
        //     The third argument.
        //
        //   arg4:
        //     The fourth argument.
        public DataRowAttribute(object? arg1, object? arg2, object? arg3, object? arg4)
        {
            Data = new object[4] { arg1, arg2, arg3, arg4 };
        }

        //
        // Summary:
        //     Initializes a new instance of the Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute
        //     class which takes in an array of arguments.
        //
        // Parameters:
        //   arg1:
        //     The first argument.
        //
        //   arg2:
        //     The second argument.
        //
        //   arg3:
        //     The third argument.
        //
        //   arg4:
        //     The fourth argument.
        //
        //   arg5:
        //     The fifth argument.
        public DataRowAttribute(object? arg1, object? arg2, object? arg3, object? arg4, object? arg5)
        {
            Data = new object[5] { arg1, arg2, arg3, arg4, arg5 };
        }

        //
        // Summary:
        //     Initializes a new instance of the Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute
        //     class which takes in an array of arguments.
        //
        // Parameters:
        //   arg1:
        //     The first argument.
        //
        //   arg2:
        //     The second argument.
        //
        //   arg3:
        //     The third argument.
        //
        //   arg4:
        //     The fourth argument.
        //
        //   arg5:
        //     The fifth argument.
        //
        //   arg6:
        //     The sixth argument.
        public DataRowAttribute(object? arg1, object? arg2, object? arg3, object? arg4, object? arg5, object? arg6)
        {
            Data = new object[6] { arg1, arg2, arg3, arg4, arg5, arg6 };
        }

        //
        // Summary:
        //     Initializes a new instance of the Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute
        //     class which takes in an array of arguments.
        //
        // Parameters:
        //   arg1:
        //     The first argument.
        //
        //   arg2:
        //     The second argument.
        //
        //   arg3:
        //     The third argument.
        //
        //   arg4:
        //     The fourth argument.
        //
        //   arg5:
        //     The fifth argument.
        //
        //   arg6:
        //     The sixth argument.
        //
        //   arg7:
        //     The seventh argument.
        public DataRowAttribute(object? arg1, object? arg2, object? arg3, object? arg4, object? arg5, object? arg6, object? arg7)
        {
            Data = new object[7] { arg1, arg2, arg3, arg4, arg5, arg6, arg7 };
        }

        //
        // Summary:
        //     Initializes a new instance of the Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute
        //     class which takes in an array of arguments.
        //
        // Parameters:
        //   arg1:
        //     The first argument.
        //
        //   arg2:
        //     The second argument.
        //
        //   arg3:
        //     The third argument.
        //
        //   arg4:
        //     The fourth argument.
        //
        //   arg5:
        //     The fifth argument.
        //
        //   arg6:
        //     The sixth argument.
        //
        //   arg7:
        //     The seventh argument.
        //
        //   arg8:
        //     The eight argument.
        public DataRowAttribute(object? arg1, object? arg2, object? arg3, object? arg4, object? arg5, object? arg6, object? arg7, object? arg8)
        {
            Data = new object[8] { arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8 };
        }

        //
        // Summary:
        //     Initializes a new instance of the Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute
        //     class which takes in an array of arguments.
        //
        // Parameters:
        //   arg1:
        //     The first argument.
        //
        //   arg2:
        //     The second argument.
        //
        //   arg3:
        //     The third argument.
        //
        //   arg4:
        //     The fourth argument.
        //
        //   arg5:
        //     The fifth argument.
        //
        //   arg6:
        //     The sixth argument.
        //
        //   arg7:
        //     The seventh argument.
        //
        //   arg8:
        //     The eight argument.
        //
        //   arg9:
        //     The nineth argument.
        public DataRowAttribute(object? arg1, object? arg2, object? arg3, object? arg4, object? arg5, object? arg6, object? arg7, object? arg8, object? arg9)
        {
            Data = new object[9] { arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9 };
        }

        //
        // Summary:
        //     Initializes a new instance of the Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute
        //     class which takes in an array of arguments.
        //
        // Parameters:
        //   arg1:
        //     The first argument.
        //
        //   arg2:
        //     The second argument.
        //
        //   arg3:
        //     The third argument.
        //
        //   arg4:
        //     The fourth argument.
        //
        //   arg5:
        //     The fifth argument.
        //
        //   arg6:
        //     The sixth argument.
        //
        //   arg7:
        //     The seventh argument.
        //
        //   arg8:
        //     The eight argument.
        //
        //   arg9:
        //     The nineth argument.
        //
        //   arg10:
        //     The tenth argument.
        public DataRowAttribute(object? arg1, object? arg2, object? arg3, object? arg4, object? arg5, object? arg6, object? arg7, object? arg8, object? arg9, object? arg10)
        {
            Data = new object[10] { arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10 };
        }

        //
        // Summary:
        //     Initializes a new instance of the Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute
        //     class which takes in an array of arguments.
        //
        // Parameters:
        //   arg1:
        //     The first argument.
        //
        //   arg2:
        //     The second argument.
        //
        //   arg3:
        //     The third argument.
        //
        //   arg4:
        //     The fourth argument.
        //
        //   arg5:
        //     The fifth argument.
        //
        //   arg6:
        //     The sixth argument.
        //
        //   arg7:
        //     The seventh argument.
        //
        //   arg8:
        //     The eight argument.
        //
        //   arg9:
        //     The nineth argument.
        //
        //   arg10:
        //     The tenth argument.
        //
        //   arg11:
        //     The eleventh argument.
        public DataRowAttribute(object? arg1, object? arg2, object? arg3, object? arg4, object? arg5, object? arg6, object? arg7, object? arg8, object? arg9, object? arg10, object? arg11)
        {
            Data = new object[11]
            {
                arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10,
                arg11
            };
        }

        //
        // Summary:
        //     Initializes a new instance of the Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute
        //     class which takes in an array of arguments.
        //
        // Parameters:
        //   arg1:
        //     The first argument.
        //
        //   arg2:
        //     The second argument.
        //
        //   arg3:
        //     The third argument.
        //
        //   arg4:
        //     The fourth argument.
        //
        //   arg5:
        //     The fifth argument.
        //
        //   arg6:
        //     The sixth argument.
        //
        //   arg7:
        //     The seventh argument.
        //
        //   arg8:
        //     The eight argument.
        //
        //   arg9:
        //     The nineth argument.
        //
        //   arg10:
        //     The tenth argument.
        //
        //   arg11:
        //     The eleventh argument.
        //
        //   arg12:
        //     The twelfth argument.
        public DataRowAttribute(object? arg1, object? arg2, object? arg3, object? arg4, object? arg5, object? arg6, object? arg7, object? arg8, object? arg9, object? arg10, object? arg11, object? arg12)
        {
            Data = new object[12]
            {
                arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10,
                arg11, arg12
            };
        }

        //
        // Summary:
        //     Initializes a new instance of the Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute
        //     class which takes in an array of arguments.
        //
        // Parameters:
        //   arg1:
        //     The first argument.
        //
        //   arg2:
        //     The second argument.
        //
        //   arg3:
        //     The third argument.
        //
        //   arg4:
        //     The fourth argument.
        //
        //   arg5:
        //     The fifth argument.
        //
        //   arg6:
        //     The sixth argument.
        //
        //   arg7:
        //     The seventh argument.
        //
        //   arg8:
        //     The eight argument.
        //
        //   arg9:
        //     The nineth argument.
        //
        //   arg10:
        //     The tenth argument.
        //
        //   arg11:
        //     The eleventh argument.
        //
        //   arg12:
        //     The twelfth argument.
        //
        //   arg13:
        //     The thirteen argument.
        public DataRowAttribute(object? arg1, object? arg2, object? arg3, object? arg4, object? arg5, object? arg6, object? arg7, object? arg8, object? arg9, object? arg10, object? arg11, object? arg12, object? arg13)
        {
            Data = new object[13]
            {
                arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10,
                arg11, arg12, arg13
            };
        }

        //
        // Summary:
        //     Initializes a new instance of the Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute
        //     class which takes in an array of arguments.
        //
        // Parameters:
        //   arg1:
        //     The first argument.
        //
        //   arg2:
        //     The second argument.
        //
        //   arg3:
        //     The third argument.
        //
        //   arg4:
        //     The fourth argument.
        //
        //   arg5:
        //     The fifth argument.
        //
        //   arg6:
        //     The sixth argument.
        //
        //   arg7:
        //     The seventh argument.
        //
        //   arg8:
        //     The eight argument.
        //
        //   arg9:
        //     The nineth argument.
        //
        //   arg10:
        //     The tenth argument.
        //
        //   arg11:
        //     The eleventh argument.
        //
        //   arg12:
        //     The twelfth argument.
        //
        //   arg13:
        //     The thirteen argument.
        //
        //   arg14:
        //     The fourteenth argument.
        public DataRowAttribute(object? arg1, object? arg2, object? arg3, object? arg4, object? arg5, object? arg6, object? arg7, object? arg8, object? arg9, object? arg10, object? arg11, object? arg12, object? arg13, object? arg14)
        {
            Data = new object[14]
            {
                arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10,
                arg11, arg12, arg13, arg14
            };
        }

        //
        // Summary:
        //     Initializes a new instance of the Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute
        //     class which takes in an array of arguments.
        //
        // Parameters:
        //   arg1:
        //     The first argument.
        //
        //   arg2:
        //     The second argument.
        //
        //   arg3:
        //     The third argument.
        //
        //   arg4:
        //     The fourth argument.
        //
        //   arg5:
        //     The fifth argument.
        //
        //   arg6:
        //     The sixth argument.
        //
        //   arg7:
        //     The seventh argument.
        //
        //   arg8:
        //     The eight argument.
        //
        //   arg9:
        //     The nineth argument.
        //
        //   arg10:
        //     The tenth argument.
        //
        //   arg11:
        //     The eleventh argument.
        //
        //   arg12:
        //     The twelfth argument.
        //
        //   arg13:
        //     The thirteen argument.
        //
        //   arg14:
        //     The fourteenth argument.
        //
        //   arg15:
        //     The fifteenth argument.
        public DataRowAttribute(object? arg1, object? arg2, object? arg3, object? arg4, object? arg5, object? arg6, object? arg7, object? arg8, object? arg9, object? arg10, object? arg11, object? arg12, object? arg13, object? arg14, object? arg15)
        {
            Data = new object[15]
            {
                arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10,
                arg11, arg12, arg13, arg14, arg15
            };
        }

        //
        // Summary:
        //     Initializes a new instance of the Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute
        //     class which takes in an array of arguments.
        //
        // Parameters:
        //   arg1:
        //     The first argument.
        //
        //   arg2:
        //     The second argument.
        //
        //   arg3:
        //     The third argument.
        //
        //   arg4:
        //     The fourth argument.
        //
        //   arg5:
        //     The fifth argument.
        //
        //   arg6:
        //     The sixth argument.
        //
        //   arg7:
        //     The seventh argument.
        //
        //   arg8:
        //     The eight argument.
        //
        //   arg9:
        //     The nineth argument.
        //
        //   arg10:
        //     The tenth argument.
        //
        //   arg11:
        //     The eleventh argument.
        //
        //   arg12:
        //     The twelfth argument.
        //
        //   arg13:
        //     The thirteen argument.
        //
        //   arg14:
        //     The fourteenth argument.
        //
        //   arg15:
        //     The fifteenth argument.
        //
        //   arg16:
        //     The sixteenth argument.
        public DataRowAttribute(object? arg1, object? arg2, object? arg3, object? arg4, object? arg5, object? arg6, object? arg7, object? arg8, object? arg9, object? arg10, object? arg11, object? arg12, object? arg13, object? arg14, object? arg15, object? arg16)
        {
            Data = new object[16]
            {
                arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10,
                arg11, arg12, arg13, arg14, arg15, arg16
            };
        }

        public IEnumerable<object?[]> GetData(MethodInfo methodInfo)
        {
            return new object[1][] { Data };
        }

        public virtual string? GetDisplayName(MethodInfo methodInfo, object?[]? data)
        {
            if (!string.IsNullOrWhiteSpace(DisplayName))
            {
                return DisplayName;
            }

            if (data != null)
            {
                return string.Format(CultureInfo.CurrentCulture, FrameworkMessages.DataDrivenResultDisplayName, methodInfo.Name, string.Join(",", data.AsEnumerable()));
            }

            return null;
        }
    }
}
#if false // Decompilation log
'236' items in cache
------------------
Resolve: 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Found single assembly: 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Load from: 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.13\ref\net6.0\System.Runtime.dll'
------------------
Resolve: 'System.Collections, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Found single assembly: 'System.Collections, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Load from: 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.13\ref\net6.0\System.Collections.dll'
------------------
Resolve: 'System.Text.RegularExpressions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Found single assembly: 'System.Text.RegularExpressions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Load from: 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.13\ref\net6.0\System.Text.RegularExpressions.dll'
------------------
Resolve: 'System.Linq, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Found single assembly: 'System.Linq, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Load from: 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.13\ref\net6.0\System.Linq.dll'
------------------
Resolve: 'System.Threading, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Found single assembly: 'System.Threading, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
Load from: 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.13\ref\net6.0\System.Threading.dll'
#endif

**Comment by Evangelink** [comment] 2023-01-13 19:49
Hi @DanMcNamee, thanks for the issue report. I will mark this issue as duplicate of #1503 and I invite you to read specifically https://github.com/microsoft/testfx/issues/1503#issuecomment-1378463341 which hopefully will explain the reasons of this breaking change.

Would you mind commenting on the other PR? Would you mind also giving some number: number of broken tests and number or arguments so we could maybe try to find a better compromise.

**Closed by Evangelink** 2023-01-13 19:49 UTC
Labels: Needs: Triage :mag:
