### ISSUE TITLE
User should be able to execute a specific data row in case of inline data driven test 

### ISSUE THREAD

**Issue by cltshivash** [Microsoft/testfx#409] opened 2018-04-24 12:06 UTC
## Description
With data rows supported inline, the user should have a flexibility to run a specific data row and not all of them.

## Steps to reproduce
Create a testproject with inline data rows and try to execute the test.

## Expected behavior
Should be able to choose a particular data row for execution

## Actual behavior
All the data rows are executed

**Comment by jayaranigarg** [comment] 2018-12-14 06:37
Closing as duplicate of https://github.com/Microsoft/testfx/issues/464

**Closed by jayaranigarg** 2018-12-14 06:37 UTC
Labels: enhancement
