### ISSUE TITLE
'executor://mstestadapter/v2': Could not load file or assembly Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [microsoft/testfx#1463] opened 2022-12-14 10:21 UTC
## Describe the bug

We have a Unit Test project targeting net7.0 and net48 TFMs.

Updating packages from 2.2.10 to 3.0.0 works for net7.0 and throws an exception for net48 TFM.

## Steps To Reproduce

Provide the steps to reproduce the behavior:
1. Clone https://github.com/SonarSource/sonar-dotnet
2. Open https://github.com/SonarSource/sonar-dotnet/blob/master/analyzers/SonarAnalyzer.sln
3. Update https://github.com/SonarSource/sonar-dotnet/blob/master/analyzers/tests/SonarAnalyzer.UnitTest/SonarAnalyzer.UnitTest.csproj to bump versions like this
  ```
      <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.4.0" />
      <PackageReference Include="MSTest.TestAdapter" Version="3.0.0" />
      <PackageReference Include="MSTest.TestFramework" Version="3.0.0" />
  ```
4. Rebuild to discover UTs
5. Pick any test class via Test Explorer, for example `AnalysisConfigReaderTest` and run all UTs

## Expected behavior

Tests should run and succeed for net7.0 and net48 (except 3 UTs from `EnumerableExtensionsTest` - not relevant, easy to fix on our side).

## Actual behavior

Tests run for net7.0 and succeed.

Tests are not executed for net48 TFM. Error is present in output window

```
An exception occurred while invoking executor 'executor://mstestadapter/v2': Could not load file or assembly 'Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
Stack trace:
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.TestDeployment.GetDeploymentInformation(String source)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestExecutionManager.ExecuteTestsInSource(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle, String source, Boolean isDeploymentDone)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestExecutionManager.ExecuteTests(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle, Boolean isDeploymentDone)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.Execution.TestExecutionManager.RunTests(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle, TestRunCancellationToken runCancellationToken)
   at Microsoft.VisualStudio.TestPlatform.MSTest.TestAdapter.MSTestExecutor.RunTests(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.RunTestsWithTests.InvokeExecutor(LazyExtension`2 executor, Tuple`2 executorUri, RunContext runContext, IFrameworkHandle frameworkHandle)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.<>c__DisplayClass46_0.<RunTestInternalWithExecutors>b__0()
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformThread.<>c__DisplayClass0_0.<Run>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.TestPlatform.PlatformAbstractions.PlatformThread.Run(Action action, PlatformApartmentState apartmentState, Boolean waitForCompletion)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.TryToRunInStaThread(Action action, Boolean waitForCompletion)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Execution.BaseRunTests.RunTestInternalWithExecutors(IEnumerable`1 executorUriExtensionMap, Int64 totalTests)
```

**Comment by Evangelink** [comment] 2022-12-14 10:30
Hi @pavel-mikula-sonarsource,

Thanks for raising this issue. It seems likely that the error is a duplicate of #1437. 

Something changed in the order of resolution, leading to some errors with appdomain. As suggested in the linked ticket, you can either disable app domains as a workaround or rollback to previous version waiting for the `3.0.1` fix (should be there soon).

**Closed** 2022-12-14 10:31 UTC
Labels: bug, resolution-duplicate

**Comment by pavel-mikula-sonarsource** [comment] 2022-12-14 10:45
Perfect! Thank you for your quick response.

We'll wait for the next release.

**Comment by Evangelink** [comment] 2022-12-14 10:54
If I recall correctly there is no strong need for the app domains in sonar analyzers. Disabling appdomains would also speed up the test discovery and execution (you may want to test it :)).
