### ISSUE TITLE
Why does test discovery search in projects that are clearly not test projects?

### ISSUE THREAD

**Issue by StingyJack** [Microsoft/testfx#506] opened 2018-10-24 04:56 UTC
## Description
The output window lists things like 

```
[10/24/2018 12:43:39 AM Diagnostic] Discovering tests in C:\Users\astanton\AppData\Local\Temp\.NETFramework,Version=v4.5.2.AssemblyAttributes.cs

[10/24/2018 12:43:39 AM Diagnostic] Discovering tests in c:\tfs\Trunk\UnitTest\PrinterTests\obj\x64\Debug\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs

[10/24/2018 12:43:39 AM Diagnostic] Discovering tests in c:\tfs\Trunk\Source\SapModuleStuff\SAPRFCTemplate.cs
```
The third one is a class library project, but there are web application projects, windows services, console apps, winforms, wpf, etc. It looks at all of them.

## Steps to reproduce
Turn on Diagnostic level output, let test discovery run, view output window

## Expected behavior
I expect it to only look in projects marked as unit test projects. 

## Actual behavior
It looks in every code file in every project, and then some that are totally external to the solution.
In a large solution all these extra files it looks in makes discovery take a long time and is chewing up resources that I need for other things

## Environment
VS 2017 15,8 something.
Adapter is mostly the MS QualityFramework dll as MSTest2 apparently can only reliably discover all tests if we "upgrade" to package reference.

**Comment by mayankbansal018** [comment] 2018-10-25 11:48
@StingyJack , AFAIK the discovery only happens for the source(test dlls) that user provides as input to vstest.console. This most likely could be VS IDE issue, can you please share a small repro project for us to investigate.

Also can you please share details about what kind of tests are not being discovered by mstestv2 for you? It would be helpful if you can share a small project for that as well.

**Comment by StingyJack** [comment] 2018-10-25 12:14
@mayankbansal018 - #241 has several repros of the skipping of tests. The solution there wont be feasible until package ref reaches feature parity

I'm not sure if it matters whether or not its an IDE (VS 15.8.7 Enterprise) issue, its something in Test that is reporting these diagnostic messages to the output window. Live Unit Testing is turned off as well as I can turn it off (a simple on/off switch for that would have been nice instead of making us figure out how to use the current settings). I do have R# but I've always turned off the Unit Test and a few other features I dont really care for. We dont use any of the other testing frameworks.

Can you look up the message "Discovering tests in" to see where its coming from?  I cited 3 lines of examples but there are at least a few hundred of them for a solution with 150 projects.

**Comment by StingyJack** [comment] 2018-11-03 18:35
Also this is only a question if you read the title and not the rest. Kindly remove the question tag.

**Comment by karanjitsingh** [comment] 2018-11-09 07:19
@StingyJack these are logs from the VS IDE, as @mayankbansal018 said, the discovery only happens for the source (test dlls). Log this issue at https://developercommunity.visualstudio.com/ and an appropriate team will get back to you.

**Comment by StingyJack** [comment] 2018-11-09 14:10
@karanjitsingh - This is the issue page for mstest related issues, and the issue is mstest related and issues I've logged on dev comm will sometimes end up getting transferred here. 

I would say that if you think its served by a different team there (which I don't believe is true, considering the same folks tend to work tickets in both places), then you can move it there and see that it gets handled appropriately. I'm not really into doing your bureaucratic work for you. I dont appreciate the push off either.

Actually, I dont see how you even have the permission to close this as you are not listed as a member or even a contributor. 

If you find this response offensive, then I have properly echoed the sentiment and message you have given to me.

**Comment by mayankbansal018** [comment] 2018-11-11 10:13
@StingyJack , we will keep the issue open, however the IDE side issues are handled by different team from Redmond. We will investigate this confirm that it's not a fault from mstest adapter side, & will only close it if it's not.

@karanjitsingh , can you please see if you can create a repro for this, take help from [comment](https://github.com/Microsoft/testfx/issues/506#issuecomment-433027059) to see if you can create one.

**Comment by karanjitsingh** [comment] 2018-11-12 08:02
@mayankbansal018 @StingyJack, these logs do not relate to MSTestAdapter. As you mentioned logs only appear in diagnostics mode in the IDE scenario, file a bug at developer community and the folks from IDE team should pick it up.

**Closed by karanjitsingh** 2018-11-12 08:02 UTC
Labels: question

**Comment by StingyJack** [comment] 2018-11-13 04:48
@karanjitsingh  - Please do not try to make me a victim of what seems to be an imagined bureaucracy. Members in this very repository open test related issues with Visual Studio, with screenshots of visual studio, etc. I've opened intellitest issues in devcomm and had them worked by members and contributors (which you were not until a day or two ago) of this repository.

What is someone in a general VS IDE team going to do with MStest diagnostics that I have previously enabled at the direction of a member of this repository? I can tell you because I have significant experience in this area - they will do nothing. The issue will sit in triage forever like so many I've logged or be closed inappropriately.

I dont use any other testing frameworks or adapters, I cant even use MSTest2 yet. R# unit test support has always been disabled. I even try disabling LUT as much as is possible. What else in Visual Studio is going to report `Discovering tests in...` in the "Tests" output window if its not an mstest related component? Thats part of what I'm asking, because whatever that module is doing, it ain't right. But instead of even trying to answer the question, you would rather tell a lifelong customer to effectively "sod off" (not the term a New Jerseyan would actually use). And serve as an example to a coworker on how to do it.

**Comment by mayankbansal018** [comment] 2018-11-14 07:16
@StingyJack I'm not sure what to reply here, as Karan has clearly mentioned, & validated that the issue is entirely at VS IDE side.
Folks do open issues of all kind, but we do not take them until they are caused in some way by mstest adapter.
As per this issue, the mstest adapter is not even remotely in picture, & neither is the vstest platform. If the whole purpose of keeping this issue opened here is so that VS IDE folks will take a look it, or we will constantly nudge them to fix this, is a wrong expectation.
The bugs filed in developer community are actively looked on, & we ourselves have fixed, & closed plenty of them based on their severity. I agree that not all bugs are fixed, some get closed because of lack of diagnostic data , others get closed if there is a feasible workaround available, & the scenario doesn't have much merit to it.
Specifically for this issue, it is related to additional diagnostics logs, which I agree on the face of it look wrong, but IDE team can take a better look, & let us know why is it coming so.

I urge you to please file a bug there, & raise the issue if they close it w/o proper explanation.

**Comment by StingyJack** [comment] 2018-11-15 13:43
@mayankbansal018  - is a log file with the name like the one below really not in your area of responsibility?
```
vstest.console.1456.TpTrace.host.18-11-14_22-07-33_03798_22.log
```
I'm tired of filing bugs in devcomm, it has been literally unable to count or show me all of them sometime after logging the 200th one (Its > 400 now). I dont want the wrong team to look at this and this is _the_ one and only MSFT test repository. There are other VS-centric issues with testing logged here by members of this repo, and that is evidence counter to Karan's statement. Karan was not even listed a contributor until a few days ago, but needs to understand that responses and posturing like that is always going to result in a negative experience for everyone involved. Take this feedback as evidence of that.

> & the scenario doesn't have much merit to it.
Always be _very_ careful with that judgement, MSFT does not assess impact to users correctly to begin with, and there are many people who simply have a hard time explaining or communicating in general (especially in the programming field). Neither of those change the fact that someone is blocked and needs help.

**Comment by mayankbansal018** [comment] 2018-11-15 15:17
@StingyJack the log file is definitely our responsibility, but there is no mention of

> vstest.console.1456.TpTrace.host.18-11-14_22-07-33_03798_22.log

 in the beginning of this issue, & I'm not sure how does this just now came into picture in your last comment.
Your initial comment only talks about Test Window logs from VS IDE

>[10/24/2018 12:43:39 AM Diagnostic] Discovering tests in C:\Users\astanton\AppData\Local\Temp\.NETFramework,Version=v4.5.2.AssemblyAttributes.cs

> [10/24/2018 12:43:39 AM Diagnostic] Discovering tests in c:\tfs\Trunk\UnitTest\PrinterTests\obj\x64\Debug\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs

> [10/24/2018 12:43:39 AM Diagnostic] Discovering tests in c:\tfs\Trunk\Source\SapModuleStuff\SAPRFCTemplate.cs

Again if your bugs at devcomm are closed w/o proper resolution or response, then it is unfortunate, but I cannot comment on that for other teams. I've no control on how they close their bugs, but we try to diagnose the issue as best as possible, & reach the best possible solution.

Karan is relatively new to our team, & it's possible that the contributors page might not have reflected him, since he might not have pushed anything yet to testfx repo, but the folks do get permissions to take action for repo as needed, be it regarding closing an issue, or any other thing.

> There are other VS-centric issues with testing logged here by members of this repo, and that is evidence counter to Karan's statement

I'm acknowledging that fact, but that doesn't mean we want to keep those issues open, which we have analyzed, & found clearly that they are not related to _this_ repo, the current issue being a clear example.

>& the scenario doesn't have much merit to it. 

Please do not half quote me, what I said was **"others get closed if there is a feasible workaround available, & the scenario doesn't have much merit to it."**. These things can happen, if we have a scenario which is outdated, or a better solution is available for them, but **We will always provide a clear workaround, or alternative & support till the features/products life-cycle** We do not yank out the support willy-nilly, without properly updating our customers. 

> but needs to understand that responses and posturing like that is always going to result in a negative experience for everyone involved. Take this feedback as evidence of that.

We do this feedback, & will keep this in mind, we could have been more elaborate while closing this issue, & give more details on why we are doing so.

Please I do not wish to engage in further discussion regarding this.

Coming back to original issue here, can you tell me if you have any concerns with logs in "vstest.console.1456.TpTrace.host.18-11-14_22-07-33_03798_22.log", & these are what we do control, 
if yes, do file a fresh bug either _here_, or in _vstest_ repo, but please do not ask my team to fix IDE diagnostics logs.

**Comment by StingyJack** [comment] 2018-11-16 05:31
> Your initial comment only talks about Test Window logs from VS IDE

My initial comment is about what the messages in the output window for Tests are reporting. See below for a customer information sanitized version of the depicted window.
![image](https://user-images.githubusercontent.com/15381181/48599640-927d6f80-e936-11e8-9a0c-c68f768b918d.png)

>can you tell me if you have any concerns with logs .... please do not ask my team to fix IDE diagnostics logs.

I dont have concerns with the logs, and I didnt ask anyone to fix logs. Please do not fixate on the logs being the core of the issue. I had a question about whatever the **testing framework** is doing that its *reporting* in the logs.  

Here is an excerpt from a few minutes ago for a small solution. Note the discovery happening in the \Source and \Tools folders where there are no unit test projects. 
```
[11/16/2018 12:13:04 AM Informational] Logging TestHost Diagnostics in file: C:\Users\astanton\AppData\Local\Temp\vstest.console.28896.TpTrace.host.18-11-16_00-13-03_38201_7.log
[11/16/2018 12:13:04 AM Diagnostic] Discovering tests in c:\projectdev\Customer1\TrunkShared\Tools\TestHarness\Program.cs
[11/16/2018 12:13:06 AM Diagnostic] Discovering tests in c:\projectdev\Customer1\TrunkShared\UnitTest\DecoderTests\DecoderTests.cs
[11/16/2018 12:13:06 AM Diagnostic] Discovering tests in c:\projectdev\Customer1\TrunkShared\Source\CustomDecoder\Decoder.cs
[11/16/2018 12:13:07 AM Warning] No test is available in c:\projectdev\Customer1\TrunkShared\Source\CustomDecoder\Decoder.csproj c:\projectdev\Customer1\TrunkShared\Source\SerializationProvider\SerializationProvider.csproj c:\projectdev\Customer1\TrunkShared\Tools\TestHarness\TestHarness.csproj c:\projectdev\Customer1\TrunkShared\UnitTest\DecoderTests\DecoderTests.csproj. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
[11/16/2018 12:13:07 AM Informational] ========== Discover test finished: 0 found (0:00:04.2609949) ==========
```

> Please do not half quote me

I dont mean to. The & in the middle of the sentence breaks the idea up when I read it.

**Comment by StingyJack** [comment] 2018-12-02 21:19
pinging @mayankbansal018  as I forgot to do so in the above response

**Comment by singhsarab** [comment] 2018-12-06 10:45
Tagging folks from the IDE team @ManishJayaswal @AbhitejJohn 
I guess this is a known issue, is there an existing workitem to track this one?

**Comment by AbhitejJohn** [comment] 2018-12-06 23:00
@StingyJack : The "Discovering Tests in *.cs" entries are tied to a source based analyzer that quickly determines tests in a solution. This analyzer only analyzes tests in projects that have a known framework referenced (which today is MSTest, Xunit or Nunit). Although the logs would show up for all documents in the solution so we can troubleshoot, its optimized to only be parsing files from a project that refers a known test framework. Hopefully that explains things. Apologies the diagnostic logs caused a confusion - I'll file an internal bug to refines these.

**Comment by StingyJack** [comment] 2018-12-07 01:56
@AbhitejJohn - Thank you. That does explain most of it. A few follow up questions if you dont mind.

Why is it looking in files that aren't part of any project? Is that just a project system quirk? 

I dont have any references to X/Nunit or even MSTest2 in most projects, just the old QualityFramework dll. Why would it be scanning projects that dont have those references or that dont have a unit test project type guid?

**Comment by AbhitejJohn** [comment] 2018-12-07 02:41
@StingyJack : Currently we scan __all__ .cs files in the solution and optimize further processing based on references and whether its part of a project etc. We also parse MSTest V1 tests, so yes projects that reference QualityTools should start showing tests as you type. The only reason we have these in diagnostic logs is so we could troubleshoot issues where for some reason we haven't looked at an actual test file. These should be more descriptive once we get to fix the internal bug I've mentioned earlier.

**Comment by StingyJack** [comment] 2018-12-07 17:57
@AbhitejJohn  - Got it. Thanks for the explanation. This item may remain closed.
