### ISSUE TITLE
No Source Available in Test Explorer

### ISSUE THREAD

**Issue by kkohler2** [microsoft/testfx#1281] opened 2022-09-26 14:01 UTC
Visual Studio 17.3.4

1. Start Visual Studio 2022
2. Create new Nunit Test Project
3. Go to Test Explorer and run all tests => default test passes
4. Expand Test Explorer and select the generated test
BUG: No source available.

Why is the source not available?  This is a new project with no settings changed.  This should work.

Nothing I tried from https://github.com/microsoft/testfx/issues/274 resolves the issue.
<img width="856" alt="VS2022Bug_No_Source_Available" src="https://user-images.githubusercontent.com/9455088/192296115-3af7865c-8367-4f16-a0eb-dce48ca778fc.png">

**Comment by Evangelink** [comment] 2022-09-26 14:08
Hi @kkohler2,

I have just tried to repeat the steps you have described and I am not able to reproduce the issue you are describing (see screenshot below):
![image](https://user-images.githubusercontent.com/11340282/192297456-d82b8028-0e27-40dc-a3f6-897c7ebfb251.png)

Could you share a project that reproduces the issue? Could you let us know the version of VS you are using?

Also please note that this repository is linked to MSTest and not to NUnit nor Test Explorer .

**Comment by Evangelink** [comment] 2022-09-27 07:09
@kkohler2 I have been chatting with Test Explorer team and they confirmed issue was fixed so I am closing this ticket. Thank you for taking the time to raise this issue.

**Closed by Evangelink** 2022-09-27 07:09 UTC
Labels: triaged, area-external-testwindow
