### ISSUE TITLE
Release Notes are wrong

### ISSUE THREAD

**Issue by thomhurst** [microsoft/testfx#2901] opened 2024-05-22 14:00 UTC
Heya, because I'm using the new Microsoft.Testing.Platform packages, I'm getting dependabot updates for them.

However it's pulling through ancient release notes from 2018. I assume because you've got v1 tags that relate to an old version of MSTest?

![SmartSelect_20240522_150011_Gmail](https://github.com/microsoft/testfx/assets/30480171/bf526e0a-5eb4-4d74-882b-fe26ac7f6bbf)
###

**Comment by Evangelink** [comment] 2024-05-22 14:03
Hi @thomhurst,

I have no idea how dependabot is generating the release notes but clearly something is off. We do ship the new platfrom from a private mirror repo and not from here.

**Comment by thomhurst** [comment] 2024-05-22 17:16
On nuget.org the project site link links to this repository. Maybe it's due to that.

**Comment by Evangelink** [comment] 2024-05-23 11:30
I can confirm this is working by looking at this metadata. I'll discuss with the team if we can point the private repo or how to workaround this.

**Comment by Evangelink** [comment] 2024-07-10 12:32
@thomhurst I will close this issue as it should now be fixed since we have open-sourced the extra component here, the link and notes will be accurate.

**Closed by Evangelink** 2024-07-10 12:32 UTC
Labels: Needs: Triage :mag:

**Comment by thomhurst** [comment] 2024-07-17 14:14
Does commenting reopen this? I'd like to reopen because they seem to be a hybrid of different projects ATM. There are release notes that are relevent to testing platform. Then there's release notes that seem specific to MSTest. 

![Uploading Screenshot_20240717_161149_Gmail.jpg…]()

**Comment by thomhurst** [comment] 2024-07-17 15:00
I haven't actually looked into it but does the dotnet runtime repository have the same problem? They have all the extensions packages don't they, so would probably have the same problems. But if you can't fix no worries, just wanted to make you guys aware

**Comment by Evangelink** [comment] 2024-07-17 15:14
I'll sync with them but AFAIK they only have one version number for all their components.
